### ISSUE TITLE
Report Site Issue not working on at least some nightly builds

### ISSUE THREAD

**Issue by wisniewskit** [mozilla-mobile/android-components#9658] opened 2021-02-09 02:03 UTC
On my S7 Edge, I do not see the Report Site Issue option in the Fenix menu on the latest nightly build (Nightly 210208 17:01 build #2015792139). However, it does seem to work for others with other devices using the latest nightly, including running a debug build in the emulator.

Given that `adb logcat` does not reveal any logging for the reporter addon, I have to wonder if other built-in addons are also having issues with this build. And since it is only happening on some devices, I also have to wonder if it's just a "bad" build.. but I will have to wait for the next nightly update to confirm that, so I decided to file a bug just in case.

**Comment by Mugurell** [comment] 2021-02-09 07:33
I don't see the "Report site issue" button on wikipedia using the latest Nightly from store - `Nightly 210208 17:58 (Build #2015792147)`

**Comment by Mugurell** [comment] 2021-02-09 07:40
I got to see the "Report site issue" button in around 2/10 tries on the S7 but 9/10 tries on a Pixel 3 with Android 10.

Seems like a race condition somewhere..

**Comment by Mugurell** [comment] 2021-02-11 14:44
Testing this more I could only see it happening if opening the menu immediately after opening a tab.
Asked my colleagues also if they saw this reproducing at a later time and they confirmed it's an intermittent issue only seen when opening the menu very soon after opening the tab.
@wisniewskit can you confirm if this is the same situation for you? Does the menu shows if opening the menu after a few seconds after the tab has loaded?

After following all behavior in Fenix and AC I think it's expected to not see the "Report site issue" if opening the menu immediately after opening a new tab.

I saw that we have all the expected menu options available but in the case of the webcompat extension (and others), 
following the changes from https://github.com/mozilla-mobile/fenix/issues/15544 we will not show the extensions with page actions
until actually receiving the [onPageAction](https://github.com/mozilla-mobile/android-components/blob/41bb4b128278aac3917845d39c33d33197508431/components/support/webextensions/src/main/java/mozilla/components/support/webextensions/WebExtensionSupport.kt#L94) call 
following which we will [set the extensionState to contain in this case the webcompat extension](https://github.com/mozilla-mobile/android-components/blob/f6bc7f526c2a76644f3cf5480be83c61b0969abc/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/WebExtensionReducer.kt#L98).

If we are trying to display the menu before the `onPageAction` call
[this code](https://github.com/mozilla-mobile/android-components/blob/ac4acf893f500ebafc13dab0c6ad6d0275142070/components/browser/menu/src/main/java/mozilla/components/browser/menu/WebExtensionBrowserMenu.kt#L93-L106) will not add the webcompat extension to the menu.
Because we don't know yet if it is enabled or not (though I think this should be by default!? so maybe we can hardcode this?)
Previously, without this `enabled` check the webcompat extension (and others also) would be added everytime and be available everytime in the menu, just like any other options.

Asking @csadilek who worked last on this if there's anything that could be done or we just have to live with this.

**Comment by wisniewskit** [comment] 2021-02-11 17:33
Actually it seems to be working now for me on the latest nightly build, so maybe this was just a hiccup after all for that build. I'm not worried about the menu item needing a moment to appear on new tabs, given that the user probably needs a few seconds to even realize there is something to report.

I'm also not sure if it makes sense to pre-fill/hard-code the menu item before the built-in addon loads and can actually handle it, unless we show the item as unusable until the addon starts. That sounds like it might be more work than is worthwhile, unless we have other situations like this which would like to fix the issue.

**Comment by csadilek** [comment] 2021-02-11 18:00
@Mugurell OK looks like you verified that https://github.com/mozilla-mobile/android-components/issues/8867 is the cause of the menu item not appearing immediately. The background here is that the web archive add-on had both its browser and page action displayed at the same time which was a bug on our end: https://github.com/mozilla-mobile/fenix/issues/15544

According to MDN: "While browser actions are displayed by default, page actions are hidden by default. They can be shown for a particular tab by calling pageAction.show()". So before we always displayed the page action even if not enabled which wasn't correct and a bug relative to Fennec which used to handle that correctly.

> Asking @csadilek who worked last on this if there's anything that could be done or we just have to live with this.
I think, if this is all to it, the menu being correct eventually once the page continues loading, we are fine, but I will let @wisniewskit decide if this is good enough. I am not sure if there's something more going on though e.g. the "Report Site Issue" not showing up at all?

**Comment by Mugurell** [comment] 2021-02-12 08:06
> I am not sure if there's something more going on though e.g. the "Report Site Issue" not showing up at all?

Only saw this issue when opening the menu immediately after opening a new tab.

**Comment by Mugurell** [comment] 2021-02-19 14:09
I propose closing this based on my investigations and Thomas's response from https://github.com/mozilla-mobile/android-components/issues/9658#issuecomment-777663865.

**Closed by Mugurell** 2021-02-19 14:09 UTC
