### ISSUE TITLE
Update ObsoleteCoroutinesApi in GeckoEngineSession Release/nightly/beta 

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#1426] opened 2018-11-20 15:18 UTC
![image](https://user-images.githubusercontent.com/773158/48783011-728ada80-ecad-11e8-915e-98aeddb01bb2.png)

https://github.com/mozilla-mobile/android-components/blob/6d1202919a60ec55cd5e50f365f32c025dfa5b00/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt#L139

**Comment by pocmo** [comment] 2018-11-20 15:22
Duplicate of #1342? 😛

**Comment by Amejia481** [comment] 2018-11-20 15:29
Oops!

**Closed** 2018-11-20 15:30 UTC
Labels: <engine-gecko>, ⌨️ code
