### ISSUE TITLE
Seeking through a video re-sets the audio state and pauses video

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#4033] opened 2019-08-06 14:20 UTC
## STR
1. Play a video.
2. Move the seek bar to a different position.
3. Observe the video is no longer playing.
4. Press the play button.
5. Observe the state of the video again.

## Expected
At 3, the video should not pause (this is existing behaviour).
At 5, the video should play immediately when we press play.

## Actual
At 3, the video pauses.
At 5, the video _does not_ play after press the play button. You have to always press the play button twice.

**Comment by pocmo** [comment] 2019-08-13 12:15
What happens internally:

Media: PLAY
State: None -> Playing
Service Start
Requesting audio Focus (1; AUDIOFOCUS_GAIN)

Media: PAUSE
State: Playing -> Pause

Media: SEEKING
State: Pause-> None
Service stopped

Media: PLAY
State: None -> Playing
Service started
Requesting audio focus (1; AUDIOFOCUS_GAIN)

Audio Focus change (-1; AUDIOFOCUS_LOSS)
Pausing media
Media: PAUSE
State: Playing -> Pause

**Comment by pocmo** [comment] 2019-08-13 12:17
Two observations:
* Should we stay in playing/pause state while seeking and not go back to none?
* Why do we receive AUDIOFOCUS_LOSS just after GAIN? Do we have multiple media sessions?

**Comment by pocmo** [comment] 2019-08-13 12:45
This also makes me realize that we did not implement any abandonAudioFocus() calls. I'll start with that.

**Comment by pocmo** [comment] 2019-08-13 13:02
Correctly abandoning and then re-requesting audio focus definitely fixes the issue.

The notification briefly disappears while the seek happens. So we could still keep the playing state while seeking.

**Comment by pocmo** [comment] 2019-08-13 16:28
> Correctly abandoning and then re-requesting audio focus definitely fixes the issue.
> 
> The notification briefly disappears while the seek happens. So we could still keep the playing state while seeking.

I'll leave it at that for now and close this issue. The issue is fixed with correctly abandoning and re-focusing. Keeping the state is more complicated and may not be necessary for now.

**Closed by pocmo** 2019-08-13 16:28 UTC
Labels: <media>, 🌐 reference browser, 🐞 bug

**Comment by jonalmeida** [comment] 2019-08-14 16:14
@pocmo on r-b after this change, videos don't seem to play anymore. I'm not sure if it's related to this one though.

**Comment by pocmo** [comment] 2019-08-14 16:23
@jonalmeida Mh, YouTube and Vimeo still seem to work here. Can you file this separately so that we can look into it?
