### ISSUE TITLE
ReaderView renders with default appearance settings after ReaderViewConfig is garbage collected

### ISSUE THREAD

**Issue by korbel** [mozilla-mobile/android-components#10082] opened 2021-04-13 13:28 UTC
Please see this fenix issue for details: https://github.com/mozilla-mobile/fenix/issues/17865

The ReaderViewConfig is a WeakReference which gets garbage collected after a while if we switch to a different tab.
After switching back to the reader view tab, it receives a port message and redraws the content with a default config.
This behavior was introduced with this PR: https://github.com/mozilla-mobile/android-components/pull/8962

**Comment by csadilek** [comment] 2021-04-20 16:54
Thanks for looking into this, @korbel. The root cause here is that the `ReaderViewFeature` may use an outdated port delegate via a content message handler from a previous feature instance which has since been garbage collected.

So, this fallback logic should never trigger. We need to make sure we don't use the port delegate of a previous instance. I will assign to me and put up a fix.

**Comment by korbel** [comment] 2021-04-20 18:58
I see. Thank you for picking up this issue.

**Closed** 2021-04-20 19:57 UTC
