### ISSUE TITLE
[Bug] Discourse favicons not cached

### ISSUE THREAD

**Issue by 532910** [mozilla-mobile/android-components#6717] opened 2020-04-20 06:19 UTC
## Steps to reproduce

1. Add some Discourse instance with favicon to Top Sites.
2. Close tab.
3. Restart Xenix.

### Expected behavior
Favicon should be shown

### Actual behavior
No favicon

### Device information

* Android 9 (LineageOS 16.0), device: OP3T
* Fenix version: 4.2.1 (Build #20941431)

**Comment by jonalmeida** [comment] 2020-04-24 22:15
I can see the icon show up with the demo Discourse forum, so I imagine it's something related to those forum's in particular.

<img width="431" alt="Screen Shot 2020-04-24 at 6 14 15 PM" src="https://user-images.githubusercontent.com/1370580/80261073-6e5bad00-8657-11ea-8c66-dcfb8dab82d2.png">

**Comment by 532910** [comment] 2020-04-24 23:08
should close try.discourse.org tab and restart firefox

**Comment by jonalmeida** [comment] 2020-04-25 01:32
> you should close try.discourse.org tab and restart firefox

I'm still able to see the icon on top sites. Could you try this on the latest nightly?

**Comment by 532910** [comment] 2020-04-25 02:13
Indded. It's not a discourse issue. I've cleared cache and now it saves discourse favicons, but does not save gitlab favicon. Looks like it saves only the first three icons and drops other on restart.
I can't reproduce this issue on the latest nightly.

**Comment by jonalmeida** [comment] 2020-04-27 20:42
Great! I'll close this then. 🙂

**Closed by jonalmeida** 2020-04-27 20:42 UTC
Labels: <icons>

**Comment by 532910** [comment] 2020-04-28 01:39
The bug is still present, please reopen!

**Comment by jonalmeida** [comment] 2020-04-28 07:31
> I can't reproduce this issue on the latest nightly.

@532910 sorry, did I misunderstand? If the bug is no longer reproducible it should be fixed with the next release of Fenix (5.0 most likely).

Please let me know and we can re-open this otherwise. :)

**Comment by 532910** [comment] 2020-05-01 16:35
This bug is reproducible on 4.3.0, but I'm unable to do in nightly.
I'm pretty sure it will not be fixed with update to 5.0.

**Comment by jonalmeida** [comment] 2020-05-04 18:19
>  I'm pretty sure it will not be fixed with update to 5.0.

If the issue isn't fixed, please comment here and we can re-open the bug.

**Comment by 532910** [comment] 2020-05-04 18:27
I've cleaned storage completely and not it works. Crap!
