### ISSUE TITLE
[Bug] Media notification is triggered by gif

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/android-components#4253] opened 2019-08-28 19:31 UTC
## Steps to reproduce
open https://mobile.twitter.com/discordapp/status/1166790936954671104
### Expected behavior
no media notification visible
### Actual behavior
media notification is visible
![Screenshot_20190828-222847_Firefox_Nightly](https://user-images.githubusercontent.com/922368/63886566-70477080-c9e3-11e9-9e77-fa0bfd9e1ec6.png)

### Device information

* Android device: OnePlus5t
* Fenix version: latest nightly

**Comment by pocmo** [comment] 2019-08-29 12:05
> Should we should the notification if the video is muted, autoplaying, with no controls?

Probably not. I need to check if we have everything to detect that. Nominated the ticket for triage.

**Comment by pocmo** [comment] 2019-09-05 12:37
I can't reproduce this with the twitter link above (anymore?). However I think I can see something similar on giphy.com.

I'm undecided whether we should show a notification for muted video. It may not play any audio but it is still potentially using traffic, e.g. when actually streaming a video. Of course there are other way how we could consider fixing that (e.g. pausing muted video when the app goes to the background; but the app could also be in the foreground and just a different tab is selected).

@topotropic What's your take from UX side? Should we show a media notification for all playing media content or limit that based on whether the media is muted (or other states)?

**Comment by NotWoods** [comment] 2019-11-03 22:57
I'm thinking that we shouldn't run videos in the background if they're muted, since there's nothing to see or listen to. This would also be the case when on a different tab. We had someone note that they accidentally consumed 7GB of data because they didn't notice a video started playing on their phone before going to bed.

**Comment by andreicristianpetcu** [comment] 2019-11-04 04:06
If it's the main active tab and thescreen is locked then thevideo should play @NotWoods 

A lot of people listen to music on youtube in Fennec https://addons.mozilla.org/en-US/firefox/addon/video-background-play-fix/

**Comment by NotWoods** [comment] 2019-11-04 16:08
I agree that videos on the active tab should always play. I just think that muted videos (not those playing audio) shouldn't play when the tab isn't active.

**Comment by topotropic** [comment] 2019-11-04 20:38
@pocmo apologies for the late reply here; I think the comments above all make sense, here's a summary:

- videos w/o sound or muted videos that are in the background should be paused
- videos with sound that are in the background continue to play and there's a media notification
- videos w or w/o sound, or muted videos in the foreground keep playing and there's a media notification

does that make sense? if so, is it feasible?

**Comment by ekager** [comment] 2020-04-11 02:22
I think this can also be closed by #6432 ?

**Comment by rocketsroger** [comment] 2020-12-10 17:13
Confirmed this is fixed on Fenix nightly.  Please verify.  Thanks

**Closed** 2020-12-10 17:14 UTC
Labels: <media>, 🐞 bug
