### ISSUE TITLE
Support CustomTabColorScheme

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#4700] opened 2019-10-09 20:08 UTC
The newer custom tabs API lets apps specify multiple color schemes: default, light, and dark. We also want to allow additional themes for private mode in Fenix (mozilla-mobile/fenix#5334).

Color schemes in AndroidX contain toolbar color, secondary toolbar color, and navigation bar color. We may want to instead store toolbar background drawable (for the private mode gradient).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3955)

**Comment by gabrielluong** [comment] 2022-10-19 17:40
Duplicate of https://github.com/mozilla-mobile/android-components/issues/8408

**Closed by gabrielluong** 2022-10-19 17:40 UTC
Labels: 🌟 feature, <customtabs>
