### ISSUE TITLE
Commiting URL with autocomplete in Fenix Search flashes just your entered text 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#3825] opened 2019-07-18 21:12 UTC
## Steps to reproduce
1. Open search in Fenix
2. Type "a" (autocompletes to "mazon.com")
3. Press enter

### Expected behavior
Autocomplete text completes and then we navigate to browser

### Actual behavior
Navigates correctly, but autocomplete text disappears and we see a flash of just "a" in the edit toolbar.

This may be because we use the EditToolbar separately from the DisplayToolbar so RB / Sample Browser would immediately transition to DisplayToolbar and wouldn't have this issue.

**Comment by mcarare** [comment] 2019-11-27 13:57
Closing this as the issue is no longer reproducible in Fenix or RB.
https://github.com/mozilla-mobile/fenix/issues/4164#issuecomment-559097237

**Closed by mcarare** 2019-11-27 13:57 UTC
Labels: <autocomplete>, help wanted, 🐉 Fenix, 🐞 bug
