### ISSUE TITLE
OutOfMemoryError: Inline autocomplete edit text

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/android-components#9320] opened 2021-01-04 20:01 UTC
```
at mozilla.components.ui.autocomplete.InlineAutocompleteEditText.onFocusChanged(InlineAutocompleteEditText.kt:6)
	at android.view.View.clearFocusInternal(View.java:6859)
	at android.view.View.clearFocus(View.java:6839)
	at android.view.ViewGroup.clearFocus(ViewGroup.java:989)
	at android.view.ViewGroup.clearFocus(ViewGroup.java:989)
	at org.mozilla.fenix.search.-$$LambdaGroup$ks$bbrxYADdH2CMKRggo9t8nEsc7Rg.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:2)
	at org.mozilla.fenix.search.SearchDialogController.handleUrlTapped(SearchDialogController.kt:1)
	at org.mozilla.fenix.search.SearchDialogInteractor.onUrlTapped(SearchDialogInteractor.kt:1)
	at org.mozilla.fenix.search.awesomebar.AwesomeBarView$loadUrlUseCase$1.invoke(AwesomeBarView.kt:1)
	at androidx.core.app.AppOpsManagerCompat.invoke$default(AppOpsManagerCompat.java:3)
	at mozilla.components.feature.awesomebar.provider.HistoryStorageSuggestionProvider$into$$inlined$zip$lambda$1.invoke(HistoryStorageSuggestionProvider.kt:1)
	at mozilla.components.browser.awesomebar.layout.-$$LambdaGroup$js$BR-_Ll3VNwGRtox30V84EZD7TdA.onClick(java-style lambda group:3)
```

https://crash-stats.mozilla.org/signature/?product=Fenix&java_stack_trace=~InlineAutocompleteEditText&signature=java.lang.OutOfMemoryError%3A%20at%20java.lang.StringFactory.newStringFromChars%28StringFactory.java%29

Related to #7886 and tracked also at bz-1652810

**Comment by rocketsroger** [comment] 2021-01-15 20:31
From the 2 reports in the last 7 days, one is when calling `clearToolbarFocus` and one is handing text change.  Both are not the cause of the OOM.  The device was running out of memory that caused the crash.  Closing as won't fix.

**Closed by rocketsroger** 2021-01-15 20:31 UTC
Labels: <autocomplete>, 💥 crash
