### ISSUE TITLE
Sample browser crashes when clicking on the toolbar with a new tab 

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#1570] opened 2018-12-12 21:41 UTC
Sample browser crashes when opening a new tab and clicking on the toolbar:

```
2018-12-12 16:37:28.883 26367-26367/org.mozilla.samples.browser E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.samples.browser, PID: 26367
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.net.MalformedURLException: unknown protocol: about
        at java.net.URL.<init>(URL.java:608)
        at java.net.URL.<init>(URL.java:498)
        at java.net.URL.<init>(URL.java:447)
        at mozilla.components.support.utils.DomainMatcherKt.basicMatch(DomainMatcher.kt:28)
        at mozilla.components.support.utils.DomainMatcherKt.segmentAwareDomainMatch(DomainMatcher.kt:17)
        at mozilla.components.browser.storage.memory.InMemoryHistoryStorage.getAutocompleteSuggestion(InMemoryHistoryStorage.kt:89)
        at mozilla.components.feature.toolbar.ToolbarAutocompleteFeature.autocomplete(ToolbarAutocompleteFeature.kt:51)
        at mozilla.components.feature.toolbar.ToolbarAutocompleteFeature.access$autocomplete(ToolbarAutocompleteFeature.kt:17)
        at mozilla.components.feature.toolbar.ToolbarAutocompleteFeature$1.invoke(ToolbarAutocompleteFeature.kt:25)
        at mozilla.components.feature.toolbar.ToolbarAutocompleteFeature$1.invoke(ToolbarAutocompleteFeature.kt:17)
        at mozilla.components.browser.toolbar.BrowserToolbar$setAutocompleteListener$1.invoke(BrowserToolbar.kt:167)
        at mozilla.components.browser.toolbar.BrowserToolbar$setAutocompleteListener$1.invoke(BrowserToolbar.kt:49)
        at mozilla.components.ui.autocomplete.InlineAutocompleteEditText$TextChangeListener.afterTextChanged(InlineAutocompleteEditText.kt:555)
        at android.widget.TextView.sendAfterTextChanged(TextView.java:9770)
        at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:12522)
        at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1273)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:576)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:506)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:36)
        at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:843)
        at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:197)
        at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:183)
        at android.view.inputmethod.InputConnectionWrapper.commitText(InputConnectionWrapper.java:169)
        at mozilla.components.ui.autocomplete.InlineAutocompleteEditText$onCreateInputConnection$1.commitText(InlineAutocompleteEditText.kt:500)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:341)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6680)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

Seems related to awesomebar but tagging both, `utils` and `awesomebar`.

**Comment by jonalmeida** [comment] 2018-12-12 21:53
It's the `java.net.URL` class that's unable to match our `about:blank` pages.

**Comment by csadilek** [comment] 2018-12-12 22:00
@jonalmeida this is a duplicate of #1502 which also has a PR up https://github.com/mozilla-mobile/android-components/pull/1569

Let's close this one?

**Closed** 2018-12-12 22:05 UTC
Labels: :iphone: sample, <utils>, 🐞 bug
