### ISSUE TITLE
TrackingCategory.SCRIPTS_AND_SUB_RESOURCES evaluates to zero

### ISSUE THREAD

**Issue by bluemarvin** [mozilla-mobile/android-components#6408] opened 2020-03-26 18:13 UTC
https://searchfox.org/mozilla-mobile/rev/98fbaf088079bcd52ea18fafe3206a25019de6d4/android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt#254

`SCRIPTS_AND_SUB_RESOURCES(1 shl 9999)` == 0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5375)

**Comment by Amejia481** [comment] 2020-03-27 14:34
This is on purpose, the category was created to mitigate a bug in Geckoview.

```kotlin
 /**
  * The [TrackingProtectionPolicy.TrackingCategory.SCRIPTS_AND_SUB_RESOURCES] is an
  * artificial category, created with the sole purpose of going around this bug
  * https://bugzilla.mozilla.org/show_bug.cgi?id=1579264, for this reason we have to
  * remove its value from the valid anti tracking categories, when is present.
  */
```
You can find more information [here](https://searchfox.org/mozilla-mobile/source/android-components/components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt#512) and [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1579264)

**Comment by bluemarvin** [comment] 2020-03-27 14:37
Then you should set it to zero and not bit shift it past the number of bits in an int. Right now SCRIPTS_AND_SUB_RESOURCES == NONE

**Comment by Amejia481** [comment] 2020-03-27 14:49
We want to differentiate from `NONE`, for this reason we try to picked a high number that geckoview wasn't going to pick as a setting.
 
  If I do `1 shl 9999 ==  0` it returns `false`
`1 shl 9999 ` is equal to `32768` [here you can run this statement](https://pl.kotl.in/-31Pry9L3).

**Comment by bluemarvin** [comment] 2020-03-27 15:14
Then java does something weird because there are only 32 bits in an integer. You are over flowing it by over 9967 bits.

**Comment by bluemarvin** [comment] 2020-03-27 15:44
32768 = 2^15 or `1 shl 15` you just got lucky that it didn't collide with on of the other bit masks.

**Comment by Amejia481** [comment] 2020-03-27 15:51
The initial intention was to find a number that wouldn't collide with any possible GeckoView combination until the issue is fix. Would you mind offering me some suggestions?

**Comment by bluemarvin** [comment] 2020-03-27 16:00
The most you can shift in Java is 0x1f (31) so if you want the last bit it should be `1 shl 31`

**Comment by Amejia481** [comment] 2020-03-27 16:05
Yes, but GeckoView could pick that number :(. But at least it is very likely that is not going to happen. Thanks

**Comment by bluemarvin** [comment] 2020-03-27 16:07
Assuming GV continues to increase the bits in order, 31 will be the last one while bit 15 as it is now will happen a lot sooner.

**Comment by Amejia481** [comment] 2020-03-27 16:11
👍

**Comment by Amejia481** [comment] 2020-03-27 16:16
Thanks for reporting the issue :)

**Comment by csadilek** [comment] 2022-10-13 20:14
This was fixed in https://github.com/mozilla-mobile/android-components/pull/7070/.

**Closed by csadilek** 2022-10-13 20:14 UTC
