### ISSUE TITLE
Keyboard Shortcuts missing/broken

### ISSUE THREAD

**Issue by frloonie** [mozilla-mobile/android-components#5211] opened 2019-12-02 13:39 UTC
It seems that in all versions of Firefox for Android some keyboard shortcuts are either missing or just not working.
Ctrl+L for selecting the address bar
Ctrl+[Number Keys] for quick switching between tabs and possibly several others. 

New tab and close tab and most of the page navigation shortcuts appear to work. 

I have this in Firefox Preview 2.3.0 (Build #13031727)
Firefox for Android 68.3.0
Fennec 68.2.0esr

**Comment by pocmo** [comment] 2019-12-02 16:32
Duplicate of #1978

**Closed by pocmo** 2019-12-02 16:32 UTC

**Comment by frloonie** [comment] 2019-12-02 18:18
I saw that issue but wasn't sure that it would be considered a duplicate as the shortcut keys they mention in that one are bringing it inline with blackberry browser and the ones I am talking about are the ones already working on desktop firefox and from what I was told on reddit, firefox for iOS.

**Comment by frloonie** [comment] 2019-12-04 21:53
@pocmo can I get clarification?
