### ISSUE TITLE
Keyboard still desyncs in InlineAutocompleteEditText

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#911] opened 2018-09-28 23:47 UTC
I'm still seeing #619:
> We've encountered desyncs between the soft keyboard and our InlineAutocompleteEditText on certain devices. Specifically, this happens when autocompleted text is deleted.

In particular, the STR:
- Tap the toolbar
- Either:
  - Type s, type backspace
  - Type st, type backspace x2
- Repeat previous step, selecting one of these at random

It's intermittent and takes me 3-4 times to reproduce.

---

I'm looking at the `deleteSurroundingText` method to investigate why our previous fix worked. I feel suspicious that we're restarting the input method at all:
https://github.com/mozilla-mobile/android-components/blob/c67f8813a5e4c300359563da6ddf8b8e128ebd0e/components/ui/autocomplete/src/main/java/mozilla/components/ui/autocomplete/InlineAutocompleteEditText.kt#L480-L481

The reasoning in the code comments is:
```kotlin
// Make the IME aware that we interrupted the deleteSurroundingText call,
// by restarting the IME.
```

However, the return value for `deleteSurroundingText` means: "true on success, false if the input connection is no longer valid." Being theoretical here, if the input connection is no longer valid, the input method will stop taking actions until the input connection is recreated. To me, this seems like a very similar effect to directly restarting the input method.

Relatedly, it seems like restarting the input method and invalidating the input connection could create a race condition, which seems like the problem we were experiencing in #619 because of the intermittent nature of the restart. Our fix, posting the restart of the input method, may reduce the occurrence of a race with a negative outcome because it prevents the two from starting simultaneously.

In practice, I don't see any negative effects on my Android emulator or on the Fire device by removing the input method restart nor do I see any tests covering this to verify why it's important.

I'll do some more blame spelunking to figure out why this was added initially (it appears to be from focus).

**Comment by mcomella** [comment] 2018-09-28 23:54
It looks like this was initially added in the original implementation of autocomplete so there isn't an extended explanation (e.g. from a regression) as to why this was necessary.

**Comment by mcomella** [comment] 2018-09-28 23:56
Also, after removing `testPostIsCalledWhenAutocompletedTextIsDeleted` (which would be unnecessary after this change), the tests pass so this behavior is not documented there either.

**Comment by mcomella** [comment] 2018-09-29 00:05
Then again, returning `true` or `false` from `deleteSurroundingText` doesn't seem to have a difference in behavior on the emulator (nor do the tests fail when the return value is changed).

**Comment by mcomella** [comment] 2018-09-29 00:05
@pocmo As the original author, do you know why we restart the input method?

**Comment by mcomella** [comment] 2018-09-29 00:10
My speculative fix is in #912.

**Comment by pocmo** [comment] 2018-10-01 10:02
It seems like this was added in #619. @Baron-Severin may have an idea what caused the issue that was fixed by this.

**Comment by pocmo** [comment] 2018-10-01 12:21
I wonder if #619 and follow-ups were caused by 0d89ea5af800bb0c8919aad224de32155ce9ecf7 (or is this completely unrelated?) which started to use `InputMethodManager.SHOW_FORCE` to workaround Fire TV not showing the keyboard for `InputMethodManager.SHOW_IMPLICIT` - which worked on all other devices (#358).

**Comment by pocmo** [comment] 2018-10-02 09:45
> The original code, which I think is the source of the problem, comes from the original focus implementation: mozilla-mobile/firefox-tv@ee6065c#diff-50902c5dd2b03ccc6f7e676eae072ffcR429

The original code was ported directly from Fennec :)
https://searchfox.org/mozilla-central/source/mobile/android/base/java/org/mozilla/gecko/toolbar/ToolbarEditText.java

So unfortunately I do not know why any of the decisions in it were made. But maybe the mozilla-central log/blame can help.

> Can you elaborate on why you think that?

It was a guess. `InputMethodManager.SHOW_FORCE` seemed to be more aggressive and continue to show the keyboard in some situations where the view wasn't focused anymore. So I was wondering if it could cause other issues.

> That being said, it seems unrelated: the act of restarting the IME as described in #911 (comment) seems to be unnecessary and seems to cause problems on certain devices since removing this line appears to fix the issue.

I'm okay with landing this if we are confident this fixes the issues we are seeing. As said above I'm not the actual author. :)

**Comment by pocmo** [comment] 2018-10-02 09:49
It looks like this was added 4 years ago in Fennec:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1023303
* https://hg.mozilla.org/mozilla-central/rev/2b89f72bc855

**Comment by pocmo** [comment] 2018-10-02 09:51
> I think it's really a bug in the 4.4 stock keyboard because the 4.4.2 stock keyboard doesn't have this problem. This patch works around it by forcing the IME to reset when we delete the autocompete text so that we're in sync with the IME.

If this is the case then this should indeed not be needed anymore. Our minSdkVersion for the components is Android 5+.

**Closed** 2018-10-03 07:47 UTC
Labels: <autocomplete>
