### ISSUE TITLE
PushError: Error: General Error: "No subscriptions created yet.")

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#5648] opened 2020-01-20 17:18 UTC
https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/7114936/

```
PushError: Error(

General Error: "No subscriptions created yet.")
    at mozilla.appservices.push.RustError.intoException(RustError.kt:4)
    at mozilla.appservices.push.PushManager.update(PushManager.kt:8)
    at mozilla.components.feature.push.RustPushConnection.updateToken(Connection.kt:19)
    at mozilla.components.feature.push.AutoPushFeature$onNewToken$1.invokeSuspend(AutoPushFeature.kt:10)
    at mozilla.components.feature.push.AutoPushFeature$onNewToken$1.invoke(AutoPushFeature.kt)
...
(6 additional frame(s) were not displayed)

Error(

General Error: "No subscriptions created yet.")
```

**Comment by pocmo** [comment] 2020-01-20 17:18
Happened in a migration build.

**Comment by jonalmeida** [comment] 2020-01-20 19:11
I think I have a general sense of what's happening with help from @jrconlin:

When we've migrated, we're getting a new token from Firebase and call `PushManager.updateToken`. However, while this works correctly, updating a token isn't possible if we haven't created a subscription before this.

So a valid code path would be: `PushManager.init` -> `PushManager.subscribe` -> `PushManager.update`

What we're seeing is: `PushManager.init` -> `PushManager.update` which is probably happening from the forced renew registration that we're doing on migration.

**Comment by jonalmeida** [comment] 2020-01-20 19:23
A-S issue filed: https://github.com/mozilla/application-services/issues/2490

**Comment by grigoryk** [comment] 2020-02-05 12:52
We landed a work-around in https://github.com/mozilla-mobile/android-components/pull/5751

**Closed by grigoryk** 2020-02-05 12:52 UTC
Labels: <migration>, blocked, 🐞 bug, 💥 crash

**Comment by ebalazs-sv** [comment] 2020-02-12 06:40
Since this is an issue that needs Sentry access, st3fan confirmed that we can move this to Done. Thanks!
