### ISSUE TITLE
Bug: IPv6 addresses are treated as search terms

### ISSUE THREAD

**Issue by dbenjaminmiller** [mozilla-mobile/android-components#8056] opened 2020-08-07 10:11 UTC
When trying to access an address such as `http://[ --- insert IPv6 server's address here]`, it seems that right now it's impossible to access such a site from the address bar.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6974)

**Comment by armujahid** [comment] 2020-12-21 10:33
Same issue is also reported at https://github.com/mozilla-mobile/fenix/issues/4343
PR https://github.com/mozilla-mobile/android-components/pull/5546 has its fix but it wasn't merged because of some performance regression.

**Comment by t-m-w** [comment] 2021-09-02 16:32
As I mentioned in [the fenix issue](https://github.com/mozilla-mobile/fenix/issues/4343#issuecomment-911850131), it is possible, but you must use HTTP AUTH notation, e.g. http://user@[::1]. The browser will warn you that the page does not require authentication and you might be getting tricked, but you can skip past it. The other workaround mentioned there is to use a bookmark.

This is a basic browser feature that is broken here. How can we get it fixed? Serious question. Bug reports are ignored, someone makes a PR, devs reject and ask users to make a bug report instead. I'm at a loss.

**Comment by NiKiZe** [comment] 2022-04-24 22:01
Just to be clear here, Firefox prefers minor performance over actually working?

**Comment by csadilek** [comment] 2022-10-13 20:43
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795150

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by csadilek** 2022-10-13 20:43 UTC
