### ISSUE TITLE
Audio focus requested (and media notification shown) for video without sound

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#4479] opened 2019-09-20 08:45 UTC
From https://bugzilla.mozilla.org/show_bug.cgi?id=1582444

> Android has this feature to stop a playing app when another one starts. In the case I have, I'm listening to some podcast or to some streaming music app, then scrolling twitter. When there's a video embedded in a tweet, Twitter starts playing it without sound.
> 
> On Firefox for Android this doesn't stop my podcast/music, but on Firefox Preview this stops it (and this is super annoying).
> 
> I think I started to get this issue after upgrading from Firefox Preview release on 69 to Firefox Preview nightly on 71. For sure it doesn't appear in Firefox for Android (on Gecko v68).

We currently show the media notification (and request audio focus) for any playing media element, completely ignoring whether this may be a video without audio track.

**Comment by Amejia481** [comment] 2019-09-23 17:29
You can try with www.cnn.com

**Comment by pocmo** [comment] 2019-10-28 16:16
Can also be reproduced with Twitter.

Currently we always request audio focus when media is playing. Comparing with Fennec it seems like Fennec does show the playing notification but does not request audio focus until audio is actually playing.

**Comment by pocmo** [comment] 2019-10-28 16:42
Opened a new GV bug to discuss moving audio focus handling back into GV:
https://bugzilla.mozilla.org/show_bug.cgi?id=1592004

Moving this issue out of the sprint until discussion has concluded.

**Comment by ekager** [comment] 2020-04-11 00:56
This sounds like a dupe of https://github.com/mozilla-mobile/fenix/issues/6146 to me. Going to close it. Please reopen if not a dupe!

**Closed by ekager** 2020-04-11 00:56 UTC
Labels: <media>, E8, P1, blocked, 🐞 bug
