### ISSUE TITLE
Fenix Crashing when Connectivity Status Changed

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#3110] opened 2019-05-24 16:47 UTC
See: https://github.com/mozilla-mobile/fenix/issues/2810

From a small investigation could be related to the `Constraints` for `RequiredNetworkType` for `WorkManager` in `PingUploadWorker` ?

**Comment by pocmo** [comment] 2019-05-24 20:11
@Dexterp37 @travis79 @mdboom `PingUploadWorker` sounds like Glean. :)

**Comment by pocmo** [comment] 2019-05-24 20:13
The stacktrace almost looks like it's a bug in workmanager.

**Comment by travis79** [comment] 2019-05-24 20:49
Thanks for the heads up, I'm looking into it.

**Comment by travis79** [comment] 2019-05-24 21:12
While this does appear to be related to WorkManager based on the stack trace, I didn't see anything there that specifically looked like it was specifically caused by Glean.  We do use WorkManager to upload pings and have a network Constraint applied, but so do other components.  

@ekager, in order to help me get to the bottom of this faster, can you please elaborate on the small investigation you performed to help me understand why you think this is caused by Glean?  Thanks!

**Comment by ekager** [comment] 2019-05-24 22:08
Hi @travis79 sorry to alarm anyone! My brief investigation was just looking through the crash report and seeing that it mentioned 'connectivity' and `PingUploadWorker` was the only file that came up when I searched, but it looks like when I search `NetworkType.Connected` there are more classes that use these constraints.

**Comment by Amejia481** [comment] 2019-05-29 19:34
@travis79  I was able to confirm that the crash is related to Glean.

In Fenix, the telemetry services are[ behind a build flag](https://github.com/mozilla-mobile/fenix/blob/2b8a3546129bc37e0d769ec264e1a71659ed26fe/app/build.gradle#L199), only activated on production builds or when a console parameter is supplied.

I activated the flag and only allow the `GleanMetricsService` to run.

[Analytics.kt#L79](https://github.com/mozilla-mobile/fenix/blob/f84b7f10dd46a3c8e2f47f87e5bf1db5687277b7/app/src/main/java/org/mozilla/fenix/components/Analytics.kt#L79)
```kotlin
    val metrics: MetricController by lazy {
        MetricController.create(
            listOf(
                GleanMetricsService(context)
//                LeanplumMetricsService(context as Application),
//                AdjustMetricsService(context)
            ),
            isTelemetryEnabled = { Settings.getInstance(context).isTelemetryEnabled }
        )
    }
```

Using a Nexus 5X API 21 emulator(Android 5.0, Google APIs x86_64), **I always get the crash**.

**STR:** [video demo](https://drive.google.com/file/d/1rUb4zwaL4bhNny_m-X7gi5fB34bGvD_4/view?usp=sharing)
 1. Navigate to a site.
 2. Turn on airplane mode.
 3. Go to the site.
 4. Turn off airplane mode.
 5. Tap on any area of the site.

When I disable the `GleanMetricsService` to run, [the crash never happens](https://drive.google.com/file/d/1hJ5I_I1xFEtFIiJEGv34g6I4eeT-d8om/view?usp=sharing).

[Analytics.kt#L79](https://github.com/mozilla-mobile/fenix/blob/f84b7f10dd46a3c8e2f47f87e5bf1db5687277b7/app/src/main/java/org/mozilla/fenix/components/Analytics.kt#L79)
```kotlin
    val metrics: MetricController by lazy {
        MetricController.create(
            listOf(
//                GleanMetricsService(context),
                LeanplumMetricsService(context as Application),
                AdjustMetricsService(context)
            ),
            isTelemetryEnabled = { Settings.getInstance(context).isTelemetryEnabled }
        )
    }
```

The issue is only happening **on Android 5.0**, it pretty likely that is a backward compatibility issue on the WorkManager library.

**Comment by pocmo** [comment] 2019-05-29 20:20
We are using version 2.0.0. There's a version 2.0.1 (and also 2.1.0-alpha01, 2.1.0-alpha02).

@Amejia481 Can you test if 2.0.1 fixes that (if not maybe one of the alphas? Although we should see if we actually want to use them).

**Comment by pocmo** [comment] 2019-05-29 20:22
This one looks similar and was fixed in 2.0.1:
https://issuetracker.google.com/issues/129226383

**Comment by Amejia481** [comment] 2019-05-29 20:44
Awesome, I will take a look at it 👍

**Comment by travis79** [comment] 2019-05-29 20:48
@Amejia481 please keep me updated on this in case I need to make any changes.  What's funny is I don't see anything in your STR that would trigger Glean to trigger sending a ping, which is what we use WorkManager for.  (On second thought, it could do it when you swipe down the shade to toggle airplane mode...  that would call `onPause()`)

**Comment by Amejia481** [comment] 2019-05-30 19:35
The `2.0.1` version fixed the issue 🎉

**Closed** 2019-05-31 15:15 UTC
Labels: <glean>, MVP Blocker, P1, 🐉 Fenix, 🐞 bug
