### ISSUE TITLE
ClassCastException: mozilla.components.concept.storage.Login cannot be cast to java.lang.Boolean

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#6677] opened 2020-04-16 13:07 UTC
> https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/7883052

```
java.lang.ClassCastException: mozilla.components.concept.storage.Login cannot be cast to java.lang.Boolean
    at mozilla.components.feature.prompts.PromptFeature.onConfirm(PromptFeature.kt:16)
    at mozilla.components.feature.prompts.dialog.LoginDialogFragment.access$onPositiveClickAction(LoginDialogFragment.kt:10)
    at -$$LambdaGroup$js$ShXO7hRzPdt_LOzUGJeIMrgdRBc.onClick(java-style lambda group:3)
    at android.view.View.performClick(View.java:6897)
    at android.widget.TextView.performClick(TextView.java:12693)
    at android.view.View$PerformClick.run(View.java:26101)
    at android.os.Handler.handleCallback(Handler.java:789)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6944)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by ekager** [comment] 2020-04-23 05:31
Dupe of #6591?

**Closed** 2020-07-27 12:56 UTC
Labels: <prompts>, 💥 crash
