### ISSUE TITLE
Use proxy for all HTTP connections in components; tooling to enforce?

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#851] opened 2018-09-24 21:49 UTC
There are some use cases where using a proxy for all connections makes sense, e.g. Tor. It'd be great if we set ourselves to do this from the get go. afaict, we're not doing that right now, e.g. https://github.com/mozilla-mobile/android-components/blob/master/components/service/fretboard/src/main/java/mozilla/components/service/fretboard/source/kinto/HttpURLConnectionHttpClient.kt doesn't seem to use a proxy.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7369)

**Comment by ncalexan** [comment] 2019-03-09 23:20
See also #1560.  This might even be a dupe of that ticket.

**Comment by csadilek** [comment] 2022-10-11 20:21
Closing and keeping https://bugzilla.mozilla.org/show_bug.cgi?id=1525486 instead to support a proxy config in GV.

**Closed by csadilek** 2022-10-11 20:21 UTC
Labels: ⌨️ code, 🔧 tooling
