### ISSUE TITLE
AutoPush warning during startup - 410 http error

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#10366] opened 2021-05-28 01:47 UTC
Seeing this locally during startup of the current Nightly:
```
                    App  W  Non-fatal error occurred in AutoPushFeature.
                         W  mozilla.appservices.push.CommunicationError: Error(Communication Error: "Unhandled client error Response { request_method: Get, url: \"https://updates.push.services.mozilla.com/v1/fcm/boxwood-axon-825/re
                            gistration/d869ce4cbc4d4631ae4a32ce3c497a7e\", status: 410, headers: Headers { headers: [Header { name: HeaderName(\"connection\"), value: \"keep-alive\" }, Header { name: HeaderName(\"content-type\"), v
                            alue: \"application/json\" }, Header { name: HeaderName(\"access-control-allow-headers\"), value: \"\" }, Header { name: HeaderName(\"content-length\"), value: \"173\" }, Header { name: HeaderName(\"acce
                            ss-control-allow-methods\"), value: \"DELETE\" }, Header { name: HeaderName(\"date\"), value: \"28 May 2021 01:43:52 GMT\" }, Header { name: HeaderName(\"server\"), value: \"nginx\" }, Header { name: Hea
                            derName(\"access-control-allow-origin\"), value: \"*\" }, Header { name: HeaderName(\"strict-transport-security\"), value: \"max-age=31536000;includeSubDomains\" }, Header { name: HeaderName(\"cache-cont
                            rol\"), value: \"max-age=86400\" }, Header { name: HeaderName(\"access-control-expose-headers\"), value: \"\" }] }, body: [123, 34, 99, 111, 100, 101, 34, 58, 32, 52, 49, 48, 44, 32, 34, 101, 114, 114, 1
                            10, 111, 34, 58, 32, 49, 48, 51, 44, 32, 34, 101, 114, 114, 111, 114, 34, 58, 32, 34, 34, 44, 32, 34, 109, 111, 114, 101, 95, 105, 110, 102, 111, 34, 58, 32, 34, 104, 116, 116, 112, 58, 47, 47, 97, 117,
                            116, 111, 112, 117, 115, 104, 46, 114, 101, 97, 100, 116, 104, 101, 100, 111, 99, 115, 46, 105, 111, 47, 101, 110, 47, 108, 97, 116, 101, 115, 116, 47, 104, 116, 116, 112, 46, 104, 116, 109, 108, 35, 101
                            , 114, 114, 111, 114, 45, 99, 111, 100, 101, 115, 34, 44, 32, 34, 109, 101, 115, 115, 97, 103, 101, 34, 58, 32, 34, 82, 101, 113, 117, 101, 115, 116, 32, 100, 105, 100, 32, 110, 111, 116, 32, 118, 97, 10
                            8, 105, 100, 97, 116, 101, 32, 85, 65, 73, 68, 32, 110, 111, 116, 32, 102, 111, 117, 110, 100, 34, 125] }")
                         W      at mozilla.appservices.push.RustError.intoException(RustError.kt:13)
                         W      at mozilla.appservices.push.PushManager.verifyConnection(PushManager.kt:13)
                         W      at mozilla.components.feature.push.RustPushConnection.verifyConnection(Connection.kt:3)
                         W      at mozilla.components.feature.push.AutoPushFeature.verifyActiveSubscriptions$feature_push_release(AutoPushFeature.kt:7)
                         W      at mozilla.components.feature.push.AutoPushFeature$tryVerifySubscriptions$1.invokeSuspend(AutoPushFeature.kt:8)
                         W      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
                         W      at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
                         W      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                         W      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                         W      at java.lang.Thread.run(Thread.java:923)
```

cc @jonalmeida

**Comment by jonalmeida** [comment] 2021-05-28 02:19
The formatted and decoded body is:

```
Unhandled client error Response { 
  request_method: Get, 
  url: "https://updates.push.services.mozilla.com/v1/fcm/boxwood-axon-825/registration/d869ce4cbc4d4631ae4a32ce3c497a7e", 
  status: 410, 
  headers: Headers { 
    headers: [
      Header { name: HeaderName("connection"), value: "keep-alive" }, 
      Header { name: HeaderName("content-type"), value: "application/json" }, 
      Header { name: HeaderName("access-control-allow-headers"), value: " },
      Header { name: HeaderName("content-length"), value: "173" },
      Header { name: HeaderName("access-control-allow-methods"), value: "DELETE" },
      Header { name: HeaderName("date"), value: "28 May 2021 01:43:52 GMT" },
      Header { name: HeaderName("server"), value: "nginx" },
      Header { name: HeaderName("access-control-allow-origin"), value: "*" },
      Header { name: HeaderName("strict-transport-security"), value: "max-age=31536000;includeSubDomains" },
      Header { name: HeaderName("cache-control"), value: "max-age=86400" },
      Header { name: HeaderName("access-control-expose-headers"), value: " }
     ] 
  }, 
  body: "{\"code\": 410, \"errno\": 103, \"error\": \"\", \"more_info\": \"http://autopush.readthedocs.io/en/latest/http.html#error-codes\", \"message\": \"Request did not validate UAID not found\"}"
```

This is a duplicate of https://github.com/mozilla-services/autopush/issues/1445. We have open Fenix issues to track this as well that are linked on the autopush issue, so I'm going to close this.

**Closed by jonalmeida** 2021-05-28 02:19 UTC
Labels: <push>
