### ISSUE TITLE
WebNotifications do not obey site permission settings

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#7161] opened 2020-05-28 20:45 UTC
In Fenix, there are reports that turning off site notifications do not stop the notifications from being delivered.

It seems we're missing that part of the system that checks the site permissions before delivering the message to the android notification manager.

**Comment by jonalmeida** [comment] 2020-05-30 01:35
With the fix from https://github.com/mozilla-mobile/android-components/issues/7164, I can see that we are still not obeying site permissions so we should still prioritize this.

**Comment by TitanNano** [comment] 2020-05-30 09:46
Yes, decent websites like Twitter are now able to let users unsubscribe from push. But subscriptions which no longer have permission, or never had, still do not obey their notification permission.

**Comment by ekager** [comment] 2020-06-01 21:25
If it helps with debugging dholbert reporting on Slack that the website sending him notifications is https://www.ksbw.com/

**Comment by jonalmeida** [comment] 2020-06-05 00:26
Looks like we need to depend on the `feature-sitepermissions` component and query the `SitePermissionsStorage.findSitePermissionsBy` before showing the notification.

Some questions I have are:
 1. Does the `origin` come from the engine itself or are we stripping it down to the host name?
 2. At a high level, this looks like we're querying the database directly, so will this mean we should do the query on a background thread if this hits IO?

Maybe @Amejia481 might know?

**Comment by Amejia481** [comment] 2020-06-05 13:13
> SitePermissionsStorage

1. We are stripping down the host name.
2. Yes, we are and it's required to do the operations in a on a background thread. I make need to make that noticeable, I opened https://github.com/mozilla-mobile/android-components/issues/7265 for it thanks for bring it up :)

**Comment by jonalmeida** [comment] 2020-06-08 18:15
Thanks Arturo!

As I started working on this, it looks like we need https://github.com/mozilla-mobile/android-components/issues/7297 in order to query the storage permissions first.

**Comment by jnachtigall** [comment] 2020-06-16 05:45
fwiw, I also still see this for twitter. See also https://www.reddit.com/r/firefox/comments/h9dvxe/how_to_disable_notifications_twitter_in_firefox/

**Comment by mvdan** [comment] 2020-06-19 12:59
I've also been encountering "breaking news!" notifications in the last couple of days, since updating to Firefox Preview 5.2 on Android. After doing some digging on Reddit and GitHub, I ended up at this thread.

I'm really surprised because I have set site notifications to "ask first", and I deleted all site exceptions yesterday. I still get those pesky notifications every few hours. What really surprises me is that I've closed all tabs, so I really don't know where the site notifications are coming from.

For now I've disabled site notifications for the entire Firefox app in the Android app notification settings. I can re-enable them if any of you would like help tracking down this issue. I haven't been able to find what site originates those notifications, because they tend to have generic titles and icons, and clicking on them doesn't open any new page.

**Comment by TitanNano** [comment] 2020-06-19 13:07
@mvdan the origin of the issue is known and a fix is in the works.

**Comment by jonalmeida** [comment] 2020-06-20 02:24
>  What really surprises me is that I've closed all tabs, so really don't know where the site notifications are coming from.

Web Notifications are mostly supported by Web Push which isn't attached to a tab, but a Service Worker in the browser.

Hoping to allocate time this next week to fix this bug.

**Closed** 2020-06-26 20:09 UTC
Labels: <webnotifications>, E3, 🐞 bug
