### ISSUE TITLE
Replace the BrowserToolbar in CustomTabsToolbarFeature with the Toolbar API

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#5475] opened 2020-01-06 16:49 UTC
We're [currently passing it the implementation][0] for the `Toolbar` API (`BrowserToolbar`) which means that apps that want to use Custom Tabs now, are bound to using our impl of the Toolbar.

There are probably some API changes we need in order to support passing in the `Toolbar` instead.

[0]: https://github.com/mozilla-mobile/android-components/blob/master/components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeature.kt#L39

**Comment by pocmo** [comment] 2020-01-07 11:15
Duplicate of #2103.

**Closed by pocmo** 2020-01-07 11:15 UTC
Labels: <customtabs>, help wanted, ⌨️ code
