### ISSUE TITLE
Fennec migration: Migration Onboarding screen is displayed if we update/replace from build 6 to build 7

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/android-components#5834] opened 2020-02-06 14:48 UTC
## Prerequisites
- Replace Fennec with Fenix build 6 - 1/16.

## Steps to reproduce
1. Replace (download and install) Fenix (build 6) with Fenix Migration (build 7) using a build from https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-nightly.2020.02.06.revision/dd16f28ac5caff5cc55d8226c7960c25da4d2384;
2. Open Fenix.

### Expected behavior
Fenix home screen is displayed (or the latest state of Fenix before the update).

### Actual behavior
The Migration Onboarding screen is displayed but the items that are being migrated are not shown.

### Device information
* Android device: Samsung Galaxy Note 8 (Android 9), Motorola Moto G6 (Android 7.0), Xiaomi Mi Pad 2 (Android 5.1) - x86 architecture.
* Fenix version: Nightly migration build 7 - 02/06.

**Comment by pocmo** [comment] 2020-02-06 14:57
In this case this is expected since we are running a follow-up migration for add-ons. Build 1-6 disabled all addons. If you install build 7 over one of them then there will be a follow-up migration that will enable supported add-ons (ublock origin).

**Comment by sflorean** [comment] 2020-02-06 15:48
Agree, in this case probably best will be to add Addons - as part of what is migrated (because nothing is shown to the users now). And for other builds, for bug-fixing (not new items migrated) the onboarding screen - to not be displayed.

**Comment by grigoryk** [comment] 2020-02-06 20:21
I agree that we should expand what we display on this screen. From the high-level migrations, we're also missing FxA.

**Comment by pocmo** [comment] 2020-02-07 10:57
Pinging @apbitner.

I agree that we could show more here. But it is also entirely possible that we have to run a follow-up migration about something that does not make sense to expose to the user because it is some weird technical detail. Maybe we need some more generic version that we can show if there's no item from our "whitelist" in the migration?

**Comment by apbitner** [comment] 2020-02-07 15:54
The items in the checklist weren't meant to be all-encompassing, they're definitely just for show. Are you suggesting a version where we don't have the checklist so it's more generic and the app would determine which version to display? How often might this happen?

**Comment by pocmo** [comment] 2020-02-07 17:05
It is likely that this will never happen at all for release users. Even on Nightly this only happened this one time and we were deliberately choosing to have it: First of all we wanted to test this flow and then we also wanted to get already migrated Nightly users to test addons. So, since it is super unlikely to happen in release (and even beta) I think we can punt on it. Even if we choose to have such a "follow-up" migration in beta/release then we can still adapt the UI for this follow-up build.

**Comment by pocmo** [comment] 2020-02-10 16:05
Okay, closing this for now: In this case it was intended - let's look at this again if we ever need to run a re-migration in beta or production.

**Closed by pocmo** 2020-02-10 16:05 UTC
Labels: <migration>

**Comment by ebalazs-sv** [comment] 2020-02-11 08:35
From the previous comment, it was concluded that this is the intended behavior. 
Due to that, I will move this to Done. Thanks!
