### ISSUE TITLE
A-C sets many `GeckoRuntimeSettings` after initial startup

### ISSUE THREAD

**Issue by snorp** [mozilla-mobile/android-components#6193] opened 2020-03-06 17:57 UTC
In [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1620105), I found that Fenix sets a ton of `GeckoRuntimeSettings` after the initial startup (not passed to `GeckoRuntime.create()`). This causes some things to spuriously re-initialized, and we know of at least one 130ms hit that we take from a Safe Browsing or Content Blocking change. GeckoView can and should de-dup these, but even after doing that I see quite a few things being set outside of the initial settings:

```
03-06 11:43:08.693 10053 10081 D GeckoViewStartup: SNORP: SetDefaultPrefs {"privacy.trackingprotection.annotate_channels":true}
03-06 11:43:08.712 10053 10081 D GeckoViewStartup: SNORP: SetDefaultPrefs {"privacy.annotate_channels.strict_list.enabled":true}
03-06 11:43:08.713 10053 10081 D GeckoViewStartup: SNORP: SetDefaultPrefs {"privacy.trackingprotection.socialtracking.enabled":true}
03-06 11:43:08.722 10053 10081 D GeckoViewStartup: SNORP: SetDefaultPrefs {"privacy.trackingprotection.cryptomining.enabled":true}
03-06 11:43:08.731 10053 10081 D GeckoViewStartup: SNORP: SetDefaultPrefs {"urlclassifier.features.cryptomining.blacklistTables":"base-cryptomining-track-digest256"}
03-06 11:43:08.738 10053 10081 D GeckoViewStartup: SNORP: SetDefaultPrefs {"privacy.trackingprotection.fingerprinting.enabled":true}
03-06 11:43:08.744 10053 10081 D GeckoViewStartup: SNORP: SetDefaultPrefs {"urlclassifier.features.fingerprinting.blacklistTables":"base-fingerprinting-track-digest256"}
03-06 11:43:08.754 10053 10081 D GeckoViewStartup: SNORP: SetDefaultPrefs {"privacy.socialtracking.block_cookies.enabled":true}
03-06 11:43:08.754 10053 10081 D GeckoViewStartup: SNORP: SetDefaultPrefs {"urlclassifier.features.socialtracking.annotate.blacklistTables":"social-tracking-protection-facebook-digest256,social-tracking-protection-linkedin-digest256,social-tracking-protection-twitter-digest256"}
03-06 11:43:08.763 10053 10081 D GeckoViewStartup: SNORP: SetDefaultPrefs {"ui.systemUsesDarkTheme":0}
03-06 11:43:08.766 10053 10081 D GeckoViewStartup: SNORP: SetDefaultPrefs {"font.size.inflation.minTwips":120}

```

If possible, these should be set with the settings passed to `GeckoRuntime.create()`, otherwise we're going to take a perf hit when they change later on.

**Comment by csadilek** [comment] 2020-03-12 19:19
The cause of this is the call to `adjustTrackingProtection` which is executed on every `onLoadRequest` via a request interceptor: https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/AppRequestInterceptor.kt#L26

I am not sure why this is still needed, as I remember us testing a fix for this. We need to remove this call anyway, as it will stop working once GV stops calling `onLoadRequest` for loads initiated by the user / by `loadUri`: https://bugzilla.mozilla.org/show_bug.cgi?id=1619796 and https://github.com/mozilla-mobile/fenix/issues/8782

**Comment by csadilek** [comment] 2020-03-13 18:51
Patch in Fenix landed to not update TP on every page load. So, closing this issue.

**Closed by csadilek** 2020-03-13 18:51 UTC
Labels: E5, 🐌 performance
