### ISSUE TITLE
[Bug] Rotating screen causes crash in samples-firefox-accounts

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/android-components#6965] opened 2020-05-13 09:22 UTC
On activity recreation `RustLogAdapter.enable` is called and throws `LogAdapterCannotEnable` error, as the adapter is already enabled.
Temporary fix in testing https://github.com/mozilla-mobile/android-components/pull/6939 was to call disable, but a better approach would be to catch the exception (or investigate if is it absolutely necessary for a-s to throw it? )

**Comment by drigio** [comment] 2020-05-14 21:18
Similar issue at #4859.

**Comment by kbrosnan** [comment] 2020-07-28 03:29
This looks like a duplicate of #4859

**Closed by kbrosnan** 2020-07-28 03:29 UTC
Labels: :iphone: sample, 🐞 bug, 💥 crash
