### ISSUE TITLE
Hide star icon on browserToolbar by default

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#6148] opened 2020-03-02 17:15 UTC
In Fenix, when we're loading a page, the "star" icon on the browserToolbar flashes for a moment then switches over to being tracking protection and the lock icon. 

![star icon 2020-03-02 09_14_46](https://user-images.githubusercontent.com/4400286/75700046-50c92300-5c66-11ea-9ce7-e60f3ccf268d.gif)

Here's a still of it:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/75700099-62aac600-5c66-11ea-914e-0b32856646f7.png">

**Comment by mcarare** [comment] 2020-03-17 13:37
Just noticed... this is a duplicate of https://github.com/mozilla-mobile/android-components/issues/4994

**Closed by mcarare** 2020-03-17 13:37 UTC
Labels: <toolbar>, 🐉 Fenix
