### ISSUE TITLE
[Crash] App crashes after installing Decentraleyes add-on and opens its moz-extension page

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/android-components#7393] opened 2020-06-15 13:14 UTC
## Steps to reproduce
1. Go to Settings - Add-ons and install Decentraleyes add-on.
2. A moz-extension page is automatically opened in a new tab.
3. Open the tab from step 2.

### Expected behavior
The moz-extension://49055b98-945e-49bd-b79b-ea4de1f22a77/pages/welcome/welcome.html page is displayed without issues.

### Actual behavior
Fenix crashes.
Reproduced it 3/3.

### Device information
* Android device: Samsung Galaxy Tab A6 (Android 9), OnePlus 5T (Android 9)
* Not reproducible on Sony Xperia Z5 Premium (Android 7.1.1)
* Fenix version: 6/15 Nightly debug build, with GV 79.0a1, AS: 60.0.0

https://crash-stats.mozilla.org/report/index/cc0d99c8-5d41-47d1-9d37-de0d60200615
https://crash-stats.mozilla.org/report/index/269d4ab6-3043-42ef-918f-4eb400200615

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6392)

**Comment by csadilek** [comment] 2020-06-15 15:04
Tried both in Sample Browser and Fenix, and can't reproduce this so far. From crashstats it looks like a web render problem, but even after enabling web render, I am not seeing the crash.

**Comment by jamienicol** [comment] 2020-06-15 17:03
Hi, I'm trying to reproduce this (for https://bugzilla.mozilla.org/show_bug.cgi?id=1645841) but I can't see Decentraleyes in the list of available addons to install in Fenix nightly. Is there something I need to do for it to appear, or a way to sideload it?

**Comment by csadilek** [comment] 2020-06-15 17:15
@jamienicol this hasn't landed it Fenix Nightly yet, unfortunately. This happened in a special build for QA. If you want to try with a local build I am happy to send along instructions. Otherwise, we should have this in Nightly soon.

**Comment by jamienicol** [comment] 2020-06-15 17:53
@csadilek Instructions would be great if it's not too much trouble!

**Comment by softvision-miralobontiu** [comment] 2020-06-16 07:06
Hi Christian,
I was able to reproduce the crash again today on 6/16 Nightly debug build #21680829, GV 79.0a1-20200614092422, AS: 60.0.0

<img src="https://user-images.githubusercontent.com/40694158/84742204-d32ce700-afb8-11ea-9a40-90f9919bd92d.gif" width="300" height="550" />

**Comment by csadilek** [comment] 2020-06-16 14:16
Thanks, @softvision-miralobontiu. We'll investigate :).

**Comment by jamienicol** [comment] 2020-06-22 11:07
I have been unable to reproduce this on my Pixel 2 (Android 9 and 10), OnePlus 6 (Android 10), or Moto G7 Play (Android 9).

@softvision-miralobontiu, if I provide you with a gecko patch with some logging added, would you be able to build Fenix with the patched gecko and attach the logcat from the crash?

**Comment by softvision-miralobontiu** [comment] 2020-06-22 12:16
@jamienicol, I was able to reproduce the crash again, today, with Samsung Galaxy Tab S6 (Android 9):

https://crash-stats.mozilla.org/report/index/bp-ba116d64-0d1d-4b43-85e6-94a8a0200622

[logcat-crash.txt](https://github.com/mozilla-mobile/android-components/files/4813099/logcat-crash.txt)

**Comment by csadilek** [comment] 2022-09-29 22:14
Tracked in https://github.com/mozilla-mobile/android-components/issues/7393.

**Closed by csadilek** 2022-09-29 22:14 UTC
Labels: 🐞 bug, blocked, needs:gv, <web-extensions>
