### ISSUE TITLE
"malformed" crash reports

### ISSUE THREAD

**Issue by snorp** [mozilla-mobile/android-components#5145] opened 2019-11-25 15:56 UTC
The top crasher for Fenix in crash-stats is marked as "malformed"[1]. The crash reporter is probably doing something wrong with those types of crashes.

[1] https://crash-stats.mozilla.com/report/index/c7c343dd-5728-4c41-b0f0-13a5f0191125

**Comment by pocmo** [comment] 2019-11-25 17:48
CC @rocketsroger 

Nominating for triage today.

**Comment by rocketsroger** [comment] 2019-11-26 19:42
Reopen to monitor the issue

**Comment by rocketsroger** [comment] 2019-12-03 16:19
From recent crashes looks like this is not related to the [INFO] tag.  From Sentry's side I can see some crashes that doesn't have a stacktrace.  
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6758032/?query=is:unresolved

**Comment by rocketsroger** [comment] 2020-01-07 19:51
Related to https://bugzilla.mozilla.org/show_bug.cgi?id=1607519.  Will monitor after fixed.

**Comment by rocketsroger** [comment] 2020-02-10 16:28
Confirmed "malformed" crash reports are not on the "Top Crashers" list.  This is now fixed.

**Closed by rocketsroger** 2020-02-10 16:28 UTC
Labels: <crash>, E5, blocked, 🐞 bug
