### ISSUE TITLE
Cannot inline bytecode built with JVM target 1.8 into bytecode... with JVM target 1.6 on upgrade to 13.0.0

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#4448] opened 2019-09-18 01:51 UTC
I upgrade FFTV to 13.0.0 and a few inline functions give me the following warning:

> Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' option

[We specify](https://searchfox.org/mozilla-mobile/rev/170b5b503d40c37c625e9f2e409d6e9a361a906b/firefox-tv/app/build.gradle#111) v1.8 in our `app/build.gradle` so I'm guessing a-c, or one of its dependents, is building with v1.6 compatibility. 🤔 However, that is not what I see [in the source](https://searchfox.org/mozilla-mobile/rev/170b5b503d40c37c625e9f2e409d6e9a361a906b/android-components/build.gradle#128).

**Comment by pocmo** [comment] 2019-09-18 12:35
I once saw this too and it disappeared - but I do not remember the details. Is this reproducible with a clean build from the command line?

**Comment by mcomella** [comment] 2019-09-19 20:41
> I once saw this too and it disappeared - but I do not remember the details. Is this reproducible with a clean build from the command line?

Yes.

> Does this happen in automation too?

I'm not sure: I opened this PR: https://github.com/mozilla-mobile/firefox-tv/pull/2880

**Comment by jonalmeida** [comment] 2019-09-20 19:34
I mentioned this offline, we bumped our kotlin version and the mismatch seems to be causing issues.

https://searchfox.org/mozilla-mobile/source/android-components/build.gradle#132-134

Adding kotlinOptions to your project should fix this. We've added a changelog entry for the 13.0.0 release as well to mention the upgrade:
```groovy
kotlinOptions {
    jvmTarget = "1.8"
}
```

**Comment by jonalmeida** [comment] 2019-09-20 21:51
Updated the changelog to show the version bump: https://github.com/mozilla-mobile/android-components/pull/4489

@mcomella mentioned it was working for him offline, so I'm going to close this issue.

**Closed by jonalmeida** 2019-09-20 21:51 UTC
Labels: 🏗️ build
