### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#11250] opened 2021-11-10 17:57 UTC
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/14791360/?referrer=github_plugin

```
NullPointerException: None
    at mozilla.appservices.logins.LoginsKt.lower(logins.kt:3)
    at mozilla.appservices.logins.LoginsKt.checkCanary(logins.kt:3)
    at mozilla.components.service.sync.logins.LoginsCrypto.getManagedKey(LoginsCrypto.kt:5)
    at mozilla.components.service.sync.logins.LoginsCrypto.key(LoginsCrypto.kt:2)
    at mozilla.components.service.sync.logins.SyncableLoginsStorage$getByBaseDomain$2.invokeSuspend(SyncableLoginsStorage.kt:2)
...
(9 additional frame(s) were not displayed)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18603)

**Comment by pocmo** [comment] 2021-11-10 18:00
This started to show up in 95.0 Beta 1 and Beta 2.

**Comment by bendk** [comment] 2021-11-15 15:06
Fairly low volume, but it would be nice to figure this one out.  On the call last week, we had a hunch it might be fixed by https://github.com/mozilla/uniffi-rs/commit/eef107bacd9981192e9d9b6c133ca19911228aca, but I don't think so.  Maybe it's caused by the same underlying issue that that was trying to address though.

I tried a few guesses at this one but they didn't trigger the issue for me:
  - I thought maybe there was an issue passing an empty string in, but those work for me when I tested.
  - I also thought maybe one of those values was null, but there seem to be null checks just before the call in android components.

I think that if we want to fix this we need to add some logging to the `checkCanary()`  function to get some more insight.

**Comment by bendk** [comment] 2022-01-24 14:59
Looks like this one is caused by just running out of memory.  I added a check in UniFFI for the rust allocation and that's regularly failing: https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/16534301/.  I seems like there's no free memory available.  Is there anything better to do in this case than throw a RuntimeError?

**Comment by bendk** [comment] 2022-01-24 15:55
It seems very likely that allocation failing was the root cause of https://github.com/mozilla/application-services/issues/4532

**Closed** 2022-10-19 23:12 UTC
Labels: <sync-logins>, a-s, 💥 crash
