### ISSUE TITLE
Allow to distinguish between main process and other process crashes in GleanCrashReporter

### ISSUE THREAD

**Issue by wcbeard** [mozilla-mobile/android-components#6013] opened 2020-02-20 22:17 UTC
#5175 made process type information available to CrashReporterService.

In order to be able to monitor a representative sample of crash rates in Fenix, it will be useful to have the process type recorded in Glean.

Incorporating this process info into the crash counts as currently implemented may require changing the existing format.

cc @travis79

**Comment by travis79** [comment] 2020-02-21 13:08
@wcbeard, I apologize for editing your title, but I wanted to make it clear what needed changed was in the `GleanCrashReporter` part of lib-crash and not in the Glean component.

**Comment by travis79** [comment] 2020-03-04 14:40
It looks like @rocketsroger has already taken care of this via the issue #5175 that was referenced.  One of the [commits/PR's associated with that](https://github.com/rocketsroger/android-components/commit/605ed466a179e5923d9723a7d3165cbf01f1e6d6) split the  `native_code_crash` labeled counter into `fatal_native_code_crash` (main process crash) and `nonfatal_native_code_crash` (content process crash).  

I don’t think that there is any further work to do here, unless I’m mistaken.

**Comment by rocketsroger** [comment] 2020-03-04 15:23
Confirmed.  This has been implemented by https://github.com/mozilla-mobile/android-components/issues/5175.  Closing.

**Closed by rocketsroger** 2020-03-04 15:23 UTC
Labels: <crash>
