### ISSUE TITLE
Investigate if ContentBlocking.AT_CONTENT is enabled somehow via AC

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#4255] opened 2019-08-29 14:19 UTC
Filed in Fenix here: https://github.com/mozilla-mobile/fenix/issues/3917

STR:
1. go to mobilenet.cz
2. click on any article with more than 4 comments
3. scroll down to comment section (called DISKUZE KE ČLÁNKU)
4. click on "NAČÍST VŠECHNY KOMENTÁŘE" (load all comments)

Expected: More comments are displayed

Actual: This is displayed: https://user-images.githubusercontent.com/2920574/60758676-3fb60c80-a01a-11e9-8747-8a099fee6799.jpg

Can reproduce in Reference Browser. Cannot reproduce in Chrome.

I could reproduce in Focus (by toggling the "Block other content trackers" - ContentBlocking.AT_CONTENT). I'm wondering if this is an AC issue where this category is being enabled somehow since Focus manages toggling the categories itself and the browsers using AC seem to have this issue.

Is there an easy way to see which categories in Gecko are currently enabled?

I thought originally it was a GV issue so I filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1563990

**Comment by Amejia481** [comment] 2019-09-05 21:22
I don't this is an AC issue, I can reproduce it using geckoview_example (with tracking protection off)
  https://tools.taskcluster.net/index/gecko.v2.mozilla-central.latest.mobile/android-api-16-debug

**Comment by Amejia481** [comment] 2019-09-05 21:46
I even created a small app that just have plain geckoview and disabled everything related to tracking protection and I still can reproduce the issue.

**Comment by pocmo** [comment] 2019-09-06 08:00
The GV team acknowledged that it seems to be a Gecko(View) bug and they are retriaging the Bugzilla issue. I'll close this AC issue for now and monitor the Bugzilla issue.

**Closed by pocmo** 2019-09-06 08:00 UTC
Labels: <engine-gecko>, 🔎 Needs investigation
