### ISSUE TITLE
Exception message missing on CrashStats?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8446] opened 2020-09-21 08:43 UTC
Here for this IllegalStateException:
https://crash-stats.mozilla.org/report/index/af4c121d-2189-4ae7-841c-2275e0200919

We get the message in Sentry ("SET SESSION: Current activity: ..."):
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9478934/?query=is%3Aunresolved

Maybe that's on purpose because crash-stats is public?

**Comment by pocmo** [comment] 2020-09-21 08:43
@rocketsroger @kbrosnan Do you know?

**Comment by rocketsroger** [comment] 2020-09-21 12:50
Looks like we don't attach the exception message to Socorro.  Only the crash stack.  I'll fix.  Thanks for noticing this.

**Comment by rocketsroger** [comment] 2020-09-22 15:18
Confirmed that this issue is due to permission.  Messages are redacted to protect user's privacy.  Closing since this is intended.

**Closed by rocketsroger** 2020-09-22 15:18 UTC
Labels: <crash>, E2
