### ISSUE TITLE
GeckoViewFetchClient seemingly sometimes corrupts request bodies

### ISSUE THREAD

**Issue by thomcc** [mozilla-mobile/android-components#2715] opened 2019-04-11 18:48 UTC
I saw this occasionally when testing the "trusted networking" features of app services. HTTPUrlConnectionClient works fine every time, but with GeckoViewFetchClient, every so often the server will indicate that our request had invalid JSON in it. I can step in the debugger and confirm that the data we pass into the request body is valid still.

Note: I don't know how to get more details here, but am totally willing to. It's possible this is somehow our fault too (the code is very new), but I'm unsure how to debug this further. If I could see the request body that actually gets sent that would be huge, but... I can't. (I can use an Interceptor, but it shows valid data, presumably because it runs before the issue occurs).

**Comment by csadilek** [comment] 2019-04-12 15:37
@thomcc do you have an example payload / request body that caused this? The good news is that we have integration tests for `GeckoViewFetchClient`. So, I am thinking of writing an end-to-end test for a specific request that failed for you. This should make it reproducible. Happy to look into it.

**Comment by pocmo** [comment] 2019-04-15 09:01
Some random thoughts:

* A randomly corrupted request body sounds like we may be using the wrong encoding?

* You should be able to see the outoing request in a connected Web IDE.

**Comment by thomcc** [comment] 2019-04-15 21:02
Are there docs on how I can connect the WebIDE?

**Comment by thomcc** [comment] 2019-04-15 21:43
This is what I see:

<img width="912" alt="Screen Shot 2019-04-15 at 2 41 41 PM" src="https://user-images.githubusercontent.com/860665/56167298-ad5b1b00-5f8c-11e9-8715-a3c7fea2199d.png">

Note: `about:debugging` doesn't seem to be able to debug requests from the main process.

**Comment by csadilek** [comment] 2019-04-15 22:20
@thomcc what app / version did you connect? The warning you got there on top suggests the runtime version is too old. Reference browser / Fenix are now using 68 (seems you had <55).

Doing this for reference browser (with remote debugging enabled) works for me. Clicking on the USB device on the right shows the Main Process and its network traffic e.g. the awesome bar requests going through GeckoView fetch:

<img width="1204" alt="Screen Shot 2019-04-15 at 6 12 46 PM" src="https://user-images.githubusercontent.com/472523/56168973-b8bd3f00-5faa-11e9-9804-66e68e8ef3e7.png">

**Comment by csadilek** [comment] 2019-04-17 01:01
Working with @vladikoff and @thomcc, we can now reproduce this consistently. We have **some** POST requests getting sent without a body although the `InputStream` was correctly passed from A-S to A-C, then read into a `ByteBuffer` and passed to GWE.

GWE also sets the `content-length` header correctly based on the size of the `ByteBuffer`, but then fails to read, and sends an empty request body. After debugging this for a while, one suspicion is the potential offset of the backing array in `ByteBuffer`. In the non-working case, we always see an offset, meaning that just consuming e.g. from `buffer.array()` (without taking the offset into account) wouldn't work as the first byte(s) will be 0.

Since GWE requires a direct `ByteBuffer` (created with `ByteBuffer.allocateDirect`), A-C doesn't seem to be able to control this offset and it would have to be taken into account on the consuming-side (in GWE)...unless GWE is just using JNI's `GetDirectBufferAddress` which should just work.

@snorp We need your help here :). Did you encounter this before (failing for some but not all streams)? Anything we're doing wrong there when creating the `ByteBuffer`: https://github.com/mozilla-mobile/android-components/blob/master/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchClient.kt#L97

**Comment by thomcc** [comment] 2019-04-17 01:04
To be more specific, AFAICT the offset is introduced for alignment. E.g. https://android.googlesource.com/platform/libcore/+/refs/heads/master/ojluni/src/main/java/java/nio/DirectByteBuffer.java#73 (or other places depending on android version AFAICT).

We seem to have some code in the tree that takes it into account (https://searchfox.org/mozilla-central/source/media/webrtc/signaling/src/media-conduit/WebrtcMediaCodecVP8VideoCodec.cpp#902-911) although most does not, for whatever reason.

**Comment by pocmo** [comment] 2019-04-17 10:00
Just opened a GV bug on Bugzilla so that it's tracked by the GV team (+ gets triaged etc.) and doesn't get lost: https://bugzilla.mozilla.org/show_bug.cgi?id=1545039

**Comment by snorp** [comment] 2019-04-17 14:07
`ByteBuffer.put` increments the position, which is probably not what you want. We use `ByteBuffer.wrap` in our tests. Still, I don't think that should cause this particular problem, since we use `GetDirectBufferAddress` in JNI to get the bytes, which AFAIK does not use the position. It's worth a try to see if that improves things, though.

**Comment by snorp** [comment] 2019-04-17 14:11
Actually nevermind, `ByteBuffer.wrap` doesn't work for direct. We do something similar to what you're doing in tests: https://searchfox.org/mozilla-central/source/mobile/android/geckoview/src/androidTest/java/org/mozilla/geckoview/test/WebExecutorTest.kt#91

Do you have any tips for reproducing this?

**Comment by vladikoff** [comment] 2019-04-17 14:36
@csadilek amazing work getting to the bottom of this and thanks for the detailed write up of the problem! 😮

**Comment by csadilek** [comment] 2019-04-17 15:53
@snorp 

> Do you have any tips for reproducing this?
I am going to try and write an integration test in A-C for this today and let you know.

If that doesn't work we can reproduce in Fenix and R-B:
- Make sure remote debugging is enabled
- Attach a debugger
- Login to Fxa
- Sync starts and will show a 400 for the POST to ...batch=true with a content-length but no body.

However, you will need the latest A-C and these changes in R-B / Fenix: 
https://github.com/thomcc/fenix/commit/df651d2db334e965e60e7164b404faab98f08d74

So, a bit tedious, let me see if I can repro in a test.

**Comment by csadilek** [comment] 2019-04-18 19:07
After more investigation, we found out that the body sent by GWE is repeating after the 4096th byte. This is now also easy to reproduce in a test: https://github.com/csadilek/android-components/commit/06e3f3b2d136fedcdfde03643412dd7fab4fb3bb

**Comment by csadilek** [comment] 2019-04-18 21:15
Fix is up in: https://phabricator.services.mozilla.com/D28095

This issue can be close once it lands.

**Comment by pocmo** [comment] 2019-04-21 18:27
Fix landed in mc/GV.

**Comment by csadilek** [comment] 2019-04-22 15:58
This is fixed now. I've verified for https://github.com/mozilla-mobile/reference-browser/pull/732

**Closed by csadilek** 2019-04-22 15:58 UTC
Labels: <engine-gecko>, <fetch>, 🐉 Fenix, 🐞 bug
