### ISSUE TITLE
Crash in [@ java.lang.IllegalStateException: at mozilla.components.browser.engine.gecko.GeckoEngineView$currentGeckoView$1.onAttachedToWindow(GeckoEngineView.kt:5)] {Display already aquired}

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/android-components#7960] opened 2020-08-03 15:47 UTC
This the third top crasher in Fenix 79b4 and 79b5 currently.

This bug is for crash report [bp-ccbba9a1-f06d-4bfb-914d-c55410200707](https://crash-stats.mozilla.org/report/index/ccbba9a1-f06d-4bfb-914d-c55410200707).

Java stack trace:
```
java.lang.IllegalStateException
	at mozilla.components.browser.engine.gecko.GeckoEngineView$currentGeckoView$1.onAttachedToWindow(GeckoEngineView.kt:5)
	at android.view.View.dispatchAttachedToWindow(View.java:19614)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3432)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3439)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3439)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3439)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3439)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3439)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3439)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3439)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3439)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3439)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3439)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2056)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1749)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7692)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
	at android.view.Choreographer.doFrame(Choreographer.java:725)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:7617)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```

bz-1651096 for crash-stats tracking

**Comment by kbrosnan** [comment] 2020-08-03 16:38
This gets sharded over a few signatures. They may have independent causes

https://crash-stats.mozilla.org/search/?java_stack_trace_raw=~Display%20already%20acquired&product=Fenix&product=Focus&_facets=signature&_sort=-date&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-signature

**Comment by pocmo** [comment] 2020-08-05 14:00
The two instances on Sentry:
* https://sentry.prod.mozaws.net/operations/fenix-fennec/issues/9257664/activity/?query=release%3Aorg.mozilla.firefox-79.0.2%20lastSeen%3A-3d%20level%3Afatal
* https://sentry.prod.mozaws.net/operations/fenix-fennec/issues/9257664/?query=release%3Aorg.mozilla.firefox-79.0.2%20lastSeen%3A-3d%20level%3Afatal

**Comment by pocmo** [comment] 2020-08-05 14:01
One thing we were planning to do is to add the `hashCode` to the exception, so that we can see, whether in this case we are seeing two `HomeActivity` (likely a leak) or the same one (maybe a fragment leak or another problem in the activity):
`ATTACH VIEW: Current activity: HomeActivity Other activity: HomeActivity`

**Comment by pocmo** [comment] 2020-08-06 15:17
Potentially interesting:
https://github.com/mozilla-mobile/android-components/issues/7871

**Comment by kbrosnan** [comment] 2020-08-10 02:51
From the dupe `java.lang.IllegalStateException: SET SESSION: Current activity: HomeActivity hashcode 223644510 Other activity: HomeActivity hashcode 12607951`

**Comment by pocmo** [comment] 2020-08-10 18:45
Maybe related: #8070 (At least also a HomeActivity leak)

**Comment by csadilek** [comment] 2020-08-10 22:21
Another HomeActivity leak: https://github.com/mozilla-mobile/fenix/issues/13479

**Comment by ebalazs-sv** [comment] 2020-08-18 13:37
This crash is reproducible on RC 79.0.5 with Pixel 2 (Android 9) following the steps:
1. Launch Fenix and set it as default browser;
2. Launch Gmail and tap on a link to open a custom tab;
3. On Fenix visit a website;
4. Crash Fenix with about:crashparent and tap Restart Firefox;
5.  Go back to the custom tab; 

The custom tab is a blank page and tapping the device back button will display the custom tab as the Fenix app. Tapping the tab counter and the opened tab, will crash Fenix.

Crash report: https://crash-stats.mozilla.org/report/index/76e10ff2-1174-4bea-979b-ae0a50200818

Not reproducible with about:crashcontent.

![20200818_163010](https://user-images.githubusercontent.com/48799384/90519685-0afb0b00-e171-11ea-9661-2b5e428c52c1.gif)

**Comment by pocmo** [comment] 2020-08-27 15:12
**Case 1**: HomeActivity and ExternalAppActivity are rendering the same session.
https://sentry.prod.mozaws.net/operations/fenix/issues/9478934/

On first sight it looks like the `ExternalAppActvity` is rendering a `null` custom tab ID, which will make it render the selected tab and then crash because that's what `HomeActivity` does too.
Weird here is that:
* We have a check for this case and `ExternalAppActivity` should exit early in this case: https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserActivity.kt#L46-L49
* Only one second before the `ExternalAppActivity` we destroyed another ``ExternalAppActivity`. But the `recreated` flag is not set on the new activity.

**Comment by pocmo** [comment] 2020-08-27 15:29
**Case 2**: [starting unknown/old HomeActivity] Home Activity and other HomeActivity rendering the same session.
https://sentry.prod.mozaws.net/operations/fenix/issues/9478934/events/891fe92c952047209bbaaab2163bdc39/

We have two Home activities. One gets used a lot, paused, resumed etc. Then it gets stopped and suddenly a different HomeActivity gets started (not created!) 12 seconds later with no trace of it before that. Where was this activity before? When was it created?

**Comment by pocmo** [comment] 2020-08-27 16:27
**Case 3** [new home activity launching, old one getting destroyed] Home Activity and other HomeActivity rendering the same session.

https://sentry.prod.mozaws.net/operations/fenix/issues/9478934/events/a6a9171228604a3080b2578e731ac42a/

We see the first HomeActivity launch (VIEW intent). Opening tabs tray. Then back to the browser. Activity gets paused and new one launches, also with VIEW intent, runs through lifecycle until resume. Then only activity continues through stop() all the way through detroy(). Then crash.

**Comment by kbrosnan** [comment] 2020-09-10 16:36
Some str involving a custom view at https://bugzilla.mozilla.org/show_bug.cgi?id=1662963

**Comment by pocmo** [comment] 2020-09-15 07:40
https://github.com/mozilla-mobile/fenix/issues/14225

**Comment by pocmo** [comment] 2020-09-16 16:38
A fix for one of them is up as PR in Fenix.

**Comment by kbrosnan** [comment] 2020-09-24 16:36
Sentry issue: [FIREFOX-BETA-52Q](https://sentry.prod.mozaws.net/operations/firefox-beta/issues/9597607/?referrer=github_plugin)

**Comment by csadilek** [comment] 2020-10-14 15:49
STRs involving PWA: https://github.com/mozilla-mobile/android-components/issues/8660#issuecomment-706285830

**Comment by csadilek** [comment] 2020-10-20 13:44
STR with two HomeActivities and private tabs: https://github.com/mozilla-mobile/fenix/issues/16053

**Comment by csadilek** [comment] 2020-11-12 21:47
Update: PWA and custom tab cases above appear to be fixed now.

Found reliable STRs involving two HomeActivities:
- Load regular tab
- Load private tab
- Tap on notification to close private tabs

This is similar to https://github.com/mozilla-mobile/fenix/issues/16053 but always reproducible so let's fix this one next.

**Comment by pocmo** [comment] 2020-12-01 17:14
Follow-up: https://github.com/mozilla-mobile/android-components/issues/9081

**Closed by pocmo** 2020-12-01 17:14 UTC
Labels: 💥 crash
