### ISSUE TITLE
Allow Fenix to pass in our own Snackbar actions for context menu

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#2811] opened 2019-04-19 22:19 UTC
Fenix is seeing some issues with the context menu snackbar and it would be great to pass in more customization of the action and snackbar style.

https://github.com/mozilla-mobile/fenix/issues/1627

https://github.com/mozilla-mobile/fenix/issues/1836

**Comment by jonalmeida** [comment] 2019-04-22 18:39
I've split this issue into two parts: one of styling and the other for actions.

Thinking off the top of my head, with the SessionFeature that observes selection changes, we shouldn't need to expose the actions so that might the problem to solve.

**Comment by ekager** [comment] 2019-04-22 21:20
So one problem I foresee is that if a user is in normal browsing and selects "Open in private tab" and then "Switch", we will need some sort of callback to update our theme accordingly on the Fenix side

**Comment by jonalmeida** [comment] 2019-04-22 22:07
Ah good point! We'd probably need to expose a hook about the session or something.

**Comment by jonalmeida** [comment] 2019-04-25 16:05
From some initial investigation into this issue and I'm able to see the tabs switching in R-B, so it doesn't look like the issue exists in the component.

**Comment by jonalmeida** [comment] 2019-04-25 19:05
@csadilek and I did some investigation and we've found the issue to be that the HomeFragment is always passing the `sessionId` for the selected session so observers on the BrowserFragment never change to the new selected session.

This is related to a previous bug I had filed as well which will also get fixed when this root cause is solved: https://github.com/mozilla-mobile/fenix/issues/1639

<br>
<br>

That is to say, this sessionId:

https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt#L112

Should be populated by the IntentProcessor only:

https://github.com/mozilla-mobile/android-components/blob/master/components/feature/intent/src/main/java/mozilla/components/feature/intent/IntentProcessor.kt#L56

<br>
<br>

After the issue is fixed I'd imagine that all `isCustomTabSession` checks should also be re-evaluated. For example: https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt#L279

**Comment by jonalmeida** [comment] 2019-04-25 19:05
@csadilek and I did some investigation and we've found the issue to be that the HomeFragment is always passing the sessionId for the selected session so observers on the BrowserFragment never change to the new selected session.

This is related to a previous bug I had filed as well which will also get fixed when this root cause is solved: mozilla-mobile/fenix#1639


That is to say, this sessionId:

https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt#L112

Should be populated by the IntentProcessor only:

https://github.com/mozilla-mobile/android-components/blob/master/components/feature/intent/src/main/java/mozilla/components/feature/intent/IntentProcessor.kt#L56


After the issue is fixed I'd imagine that all isCustomTabSession checks should also be re-evaluated. For example: https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt#L279

**Comment by jonalmeida** [comment] 2019-04-25 19:21
Another way of saying this is, if you pass a session ID to features, those features will **only operate on that session** and will ignore session selection changes.

**Comment by jonalmeida** [comment] 2019-04-26 17:09
This might be okay to close for now but I'm leaving it open for more room to comment.

**Comment by bifleming** [comment] 2019-05-07 18:36
@jonalmeida Just talked to Emily, and she thinks this is resolved. Ready to close it?

**Closed** 2019-05-07 18:43 UTC
Labels: <contextmenu>, P1, 🐉 Fenix
