### ISSUE TITLE
Migrate pinned sites

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#5823] opened 2020-02-05 19:57 UTC
Note that users can pin up to 16 sites in Fennec (after that the feature seems to break) but we don't expect the average user to have more than a few and it seems reasonable to migrate everything rather than put a cap on it.

**Comment by pocmo** [comment] 2020-02-06 12:47
This seems to be a duplicate of https://github.com/mozilla-mobile/android-components/issues/5126? :)

**Closed** 2020-02-06 13:48 UTC
Labels: <migration>
