### ISSUE TITLE
Robolectric artifacts not getting cached by toolchain task

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#7122] opened 2020-05-27 10:37 UTC
Just saw this error in a PR task:

```
[task 2020-05-27T00:15:50.965Z] SUITE: mozilla.components.feature.addons.ui.AddonsPermissionsAdapterTest
[task 2020-05-27T00:15:50.965Z]   TEST: bind permissions
[task 2020-05-27T00:15:50.965Z]     Downloading: org/robolectric/android-all/9-robolectric-4913185-2/android-all-9-robolectric-4913185-2.pom from repository sonatype at https://oss.sonatype.org/content/groups/public/
[task 2020-05-27T00:15:51.165Z]     Transferring 2K from sonatype
[task 2020-05-27T00:15:51.165Z]     Downloading: org/sonatype/oss/oss-parent/9/oss-parent-9.pom from repository sonatype at https://oss.sonatype.org/content/groups/public/
[task 2020-05-27T00:15:51.265Z]     Transferring 6K from sonatype
[task 2020-05-27T00:15:51.265Z]     Downloading: org/robolectric/android-all/9-robolectric-4913185-2/android-all-9-robolectric-4913185-2.jar from repository sonatype at https://oss.sonatype.org/content/groups/public/
[task 2020-05-27T00:15:51.465Z]     Transferring 118099K from sonatype
[task 2020-05-27T00:15:52.765Z]     Connection reset
[task 2020-05-27T00:15:52.765Z]     [WARNING] Unable to get resource 'org.robolectric:android-all:jar:9-robolectric-4913185-2' from repository sonatype (https://oss.sonatype.org/content/groups/public/): GET request of: org/robolectric/android-all/9-robolectric-4913185-2/android-all-9-robolectric-4913185-2.jar from sonatype failed
[task 2020-05-27T00:15:52.765Z]     Downloading: org/robolectric/android-all/9-robolectric-4913185-2/android-all-9-robolectric-4913185-2.jar from repository central at http://repo1.maven.org/maven2
[task 2020-05-27T00:15:52.765Z]     Error transferring file: Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/org/robolectric/android-all/9-robolectric-4913185-2/android-all-9-robolectric-4913185-2.jar
[task 2020-05-27T00:15:52.765Z]     [WARNING] Unable to get resource 'org.robolectric:android-all:jar:9-robolectric-4913185-2' from repository central (http://repo1.maven.org/maven2): Error transferring file: Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/org/robolectric/android-all/9-robolectric-4913185-2/android-all-9-robolectric-4913185-2.jar
[task 2020-05-27T00:15:52.766Z]   FAILURE
[task 2020-05-27T00:15:52.766Z] 
[task 2020-05-27T00:15:52.766Z] Unable to resolve artifact: Missing:
[task 2020-05-27T00:15:52.766Z] ----------
[task 2020-05-27T00:15:52.766Z] 1) org.robolectric:android-all:jar:9-robolectric-4913185-2
[task 2020-05-27T00:15:52.766Z] 
[task 2020-05-27T00:15:52.766Z]   Try downloading the file manually from the project website.
[task 2020-05-27T00:15:52.766Z] 
[task 2020-05-27T00:15:52.766Z]   Then, install it using the command: 
[task 2020-05-27T00:15:52.766Z]       mvn install:install-file -DgroupId=org.robolectric -DartifactId=android-all -Dversion=9-robolectric-4913185-2 -Dpackaging=jar -Dfile=/path/to/file
[task 2020-05-27T00:15:52.766Z] 
[task 2020-05-27T00:15:52.766Z]   Alternatively, if you host your own repository you can deploy the file there: 
[task 2020-05-27T00:15:52.766Z]       mvn deploy:deploy-file -DgroupId=org.robolectric -DartifactId=android-all -Dversion=9-robolectric-4913185-2 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[task 2020-05-27T00:15:52.766Z] 
[task 2020-05-27T00:15:52.766Z]   Path to dependency: 
[task 2020-05-27T00:15:52.766Z]   	1) org.apache.maven:super-pom:pom:2.0
[task 2020-05-27T00:15:52.766Z]   	2) org.robolectric:android-all:jar:9-robolectric-4913185-2
[task 2020-05-27T00:15:52.766Z] 
[task 2020-05-27T00:15:52.766Z] ----------
[task 2020-05-27T00:15:52.766Z] 1 required artifact is missing.
[task 2020-05-27T00:15:52.766Z] 
[task 2020-05-27T00:15:52.766Z] for artifact: 
[task 2020-05-27T00:15:52.766Z]   org.apache.maven:super-pom:pom:2.0
[task 2020-05-27T00:15:52.766Z] 
[task 2020-05-27T00:15:52.766Z] from the specified remote repositories:
[task 2020-05-27T00:15:52.766Z]   central (http://repo1.maven.org/maven2),
[task 2020-05-27T00:15:52.766Z]   sonatype (https://oss.sonatype.org/content/groups/public/)
```

https://firefox-ci-tc.services.mozilla.com/tasks/ZjIjRXI5QkeBUMzSr9n16A/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FZjIjRXI5QkeBUMzSr9n16A%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6099)

**Comment by pocmo** [comment] 2020-05-27 10:38
Robolectric downloads some additional artifacts on the first run. Looks like we do not cache those yet. Not sure where Robolectric saves them.

**Comment by pocmo** [comment] 2020-05-27 10:39
CC @JohanLorenzo - Something else to eventually cache. :)

**Comment by JohanLorenzo** [comment] 2020-05-27 13:33
`[task 2020-05-27T00:15:50.965Z]     Downloading: org/robolectric/android-all/9-robolectric-4913185-2/android-all-9-robolectric-4913185-2.pom from repository sonatype at https://oss.sonatype.org/content/groups/public/`

I guess we need to proxy sonatype.org too. Do you know where it should happen in `build.gradle` @pocmo?

**Comment by JohanLorenzo** [comment] 2020-05-27 14:54
Duplicate of https://github.com/mozilla-mobile/android-components/issues/6563.

**Comment by pocmo** [comment] 2020-05-27 15:04
> I guess we need to proxy sonatype.org too. Do you know where it should happen in build.gradle @pocmo?

I think this is not really happening in Gradle and Robolectric is somehow side-stepping gradle for that. This makes kind of sense since Robolectric needs to figure out at test runtime which artifacts it needs based on which SDK level you want to test against etc.

**Comment by pocmo** [comment] 2020-05-27 15:07
There are some interesting hints here:
http://robolectric.org/configuring/

```
robolectric.offline — Set to true to disable runtime fetching of jars.
robolectric.dependency.dir — When in offline mode, specifies a folder containing runtime dependencies.
robolectric.dependency.repo.id — Set the ID of the Maven repository to use for the runtime dependencies (default sonatype).
robolectric.dependency.repo.url — Set the URL of the Maven repository to use for the runtime dependencies (default https://oss.sonatype.org/content/groups/public/).
```

I guess with that we could pick a custom directory and change the repo to our proxy.

**Comment by jonalmeida** [comment] 2022-02-09 21:51
This is worth tackling still as an intermediate step if setting up our maven dependency mirror is a long term project.

**Comment by csadilek** [comment] 2022-10-14 18:45
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795376

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by csadilek** 2022-10-14 18:45 UTC
Labels: automation, 🏗️ build
