### ISSUE TITLE
Intermittent test failure in feature-customtabs - processCustomTabIntentWithAdditionalHeaders

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#9428] opened 2021-01-15 20:15 UTC
Saw this a couple of times by now.

```
[task 2021-01-15T20:08:06.256Z]   TEST: processCustomTabIntentWithAdditionalHeaders
[task 2021-01-15T20:08:06.256Z]     [Robolectric] mozilla.components.feature.customtabs.CustomTabIntentProcessorTest.processCustomTabIntentWithAdditionalHeaders: sdk=28; resources=binary
[task 2021-01-15T20:08:06.354Z]     I/MonitoringInstr: Instrumentation started!
[task 2021-01-15T20:08:06.354Z]     W Could not read from intent.
[task 2021-01-15T20:08:06.354Z]     java.lang.NullPointerException: null cannot be cast to non-null type T
[task 2021-01-15T20:08:06.354Z]     at mozilla.components.support.utils.SafeIntent$getParcelableExtra$1.invoke(SafeIntent.kt:68)
[task 2021-01-15T20:08:06.354Z]     at mozilla.components.support.utils.SafeIntent$getParcelableExtra$1.invoke(SafeIntent.kt:20)
[task 2021-01-15T20:08:06.354Z]     at mozilla.components.support.utils.SafeIntent.safeAccess(SafeIntent.kt:85)
[task 2021-01-15T20:08:06.354Z]     at mozilla.components.support.utils.SafeIntent.safeAccess$default(SafeIntent.kt:83)
[task 2021-01-15T20:08:06.354Z]     at mozilla.components.support.utils.SafeIntent.getParcelableExtra(SafeIntent.kt:67)
[task 2021-01-15T20:08:06.354Z]     at mozilla.components.feature.customtabs.CustomTabConfigHelperKt.getCloseButtonIcon(CustomTabConfigHelper.kt:115)
[task 2021-01-15T20:08:06.354Z]     at mozilla.components.feature.customtabs.CustomTabConfigHelperKt.createCustomTabConfigFromIntent(CustomTabConfigHelper.kt:93)
[task 2021-01-15T20:08:06.354Z]     at mozilla.components.feature.customtabs.CustomTabIntentProcessor.process(CustomTabIntentProcessor.kt:56)
[task 2021-01-15T20:08:06.354Z]     at mozilla.components.feature.customtabs.CustomTabIntentProcessorTest.processCustomTabIntentWithAdditionalHeaders(CustomTabIntentProcessorTest.kt:108)
[task 2021-01-15T20:08:06.354Z]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2021-01-15T20:08:06.354Z]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2021-01-15T20:08:06.355Z]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2021-01-15T20:08:06.355Z]     at java.lang.reflect.Method.invoke(Method.java:498)
[task 2021-01-15T20:08:06.355Z]     at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2021-01-15T20:08:06.355Z]     at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2021-01-15T20:08:06.355Z]     at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2021-01-15T20:08:06.355Z]     at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2021-01-15T20:08:06.355Z]     at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:601)
[task 2021-01-15T20:08:06.355Z]     at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:260)
[task 2021-01-15T20:08:06.355Z]     at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
[task 2021-01-15T20:08:06.355Z]     at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
[task 2021-01-15T20:08:06.355Z]     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[task 2021-01-15T20:08:06.355Z]     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[task 2021-01-15T20:08:06.355Z]     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[task 2021-01-15T20:08:06.355Z]     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[task 2021-01-15T20:08:06.355Z]     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[task 2021-01-15T20:08:06.355Z]     at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
[task 2021-01-15T20:08:06.355Z]     at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[task 2021-01-15T20:08:06.355Z]     at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:154)
[task 2021-01-15T20:08:06.355Z]     at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
[task 2021-01-15T20:08:06.355Z]     at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
[task 2021-01-15T20:08:06.355Z]     at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
[task 2021-01-15T20:08:06.355Z]     at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[task 2021-01-15T20:08:06.355Z]     at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
[task 2021-01-15T20:08:06.355Z]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2021-01-15T20:08:06.355Z]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2021-01-15T20:08:06.355Z]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2021-01-15T20:08:06.355Z]     at java.lang.reflect.Method.invoke(Method.java:498)
[task 2021-01-15T20:08:06.355Z]     at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2021-01-15T20:08:06.355Z]     at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2021-01-15T20:08:06.355Z]     at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
[task 2021-01-15T20:08:06.355Z]     at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
[task 2021-01-15T20:08:06.355Z]     at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
[task 2021-01-15T20:08:06.356Z]     at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
[task 2021-01-15T20:08:06.356Z]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2021-01-15T20:08:06.356Z]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2021-01-15T20:08:06.356Z]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2021-01-15T20:08:06.356Z]     at java.lang.reflect.Method.invoke(Method.java:498)
[task 2021-01-15T20:08:06.357Z]     at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2021-01-15T20:08:06.357Z]     at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2021-01-15T20:08:06.357Z]     at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
[task 2021-01-15T20:08:06.357Z]     at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
[task 2021-01-15T20:08:06.357Z]     at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
[task 2021-01-15T20:08:06.357Z]     at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[task 2021-01-15T20:08:06.357Z]     at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[task 2021-01-15T20:08:06.357Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2021-01-15T20:08:06.358Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2021-01-15T20:08:06.358Z]     at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
[task 2021-01-15T20:08:06.358Z]     at java.lang.Thread.run(Thread.java:748)
[task 2021-01-15T20:08:06.555Z]   FAILURE
[task 2021-01-15T20:08:06.555Z] 
[task 2021-01-15T20:08:06.555Z] java.lang.AssertionError: No action of type class mozilla.components.browser.state.action.EngineAction$LoadUrlAction found
[task 2021-01-15T20:08:06.556Z] 	at mozilla.components.support.test.middleware.CaptureActionsMiddleware.findFirstAction(CaptureActionsMiddleware.kt:33)
[task 2021-01-15T20:08:06.556Z] 	at mozilla.components.support.test.middleware.CaptureActionsMiddleware.assertFirstAction(CaptureActionsMiddleware.kt:54)
[task 2021-01-15T20:08:06.556Z] 	at mozilla.components.feature.customtabs.CustomTabIntentProcessorTest.processCustomTabIntentWithAdditionalHeaders(CustomTabIntentProcessorTest.kt:113)
[task 2021-01-15T20:08:06.556Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2021-01-15T20:08:06.556Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2021-01-15T20:08:06.556Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2021-01-15T20:08:06.556Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2021-01-15T20:08:06.556Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2021-01-15T20:08:06.556Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2021-01-15T20:08:06.556Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2021-01-15T20:08:06.556Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2021-01-15T20:08:06.556Z] 	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:601)
[task 2021-01-15T20:08:06.556Z] 	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:260)
[task 2021-01-15T20:08:06.556Z] 	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
[task 2021-01-15T20:08:06.556Z] 	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
[task 2021-01-15T20:08:06.556Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[task 2021-01-15T20:08:06.556Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[task 2021-01-15T20:08:06.556Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[task 2021-01-15T20:08:06.556Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[task 2021-01-15T20:08:06.556Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[task 2021-01-15T20:08:06.556Z] 	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
[task 2021-01-15T20:08:06.556Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[task 2021-01-15T20:08:06.556Z] 	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:154)
[task 2021-01-15T20:08:06.556Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
[task 2021-01-15T20:08:06.556Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
[task 2021-01-15T20:08:06.556Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
[task 2021-01-15T20:08:06.556Z] 	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[task 2021-01-15T20:08:06.556Z] 	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
[task 2021-01-15T20:08:06.557Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2021-01-15T20:08:06.557Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2021-01-15T20:08:06.557Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2021-01-15T20:08:06.557Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2021-01-15T20:08:06.557Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2021-01-15T20:08:06.557Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2021-01-15T20:08:06.557Z] 	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
[task 2021-01-15T20:08:06.557Z] 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
[task 2021-01-15T20:08:06.557Z] 	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
[task 2021-01-15T20:08:06.557Z] 	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
[task 2021-01-15T20:08:06.557Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2021-01-15T20:08:06.557Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2021-01-15T20:08:06.557Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2021-01-15T20:08:06.557Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2021-01-15T20:08:06.557Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2021-01-15T20:08:06.557Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2021-01-15T20:08:06.557Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
[task 2021-01-15T20:08:06.557Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
[task 2021-01-15T20:08:06.558Z] 	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
[task 2021-01-15T20:08:06.558Z] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[task 2021-01-15T20:08:06.558Z] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[task 2021-01-15T20:08:06.561Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2021-01-15T20:08:06.561Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2021-01-15T20:08:06.561Z] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
[task 2021-01-15T20:08:06.561Z] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Archaeopteryx** [comment] 2021-01-16 19:37
Duplicate of #9427.

**Closed by Archaeopteryx** 2021-01-16 19:37 UTC
Labels: <customtabs>, 🎲 intermittent-test
