### ISSUE TITLE
Intermittent UI test failure - java.lang.AssertionError - checkGleanClickData

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#10781] opened 2021-08-10 07:54 UTC
### Firebase Test Run:
https://console.firebase.google.com/project/moz-android-components-230120/testlab/histories/bh.acacddb44ee28c64/matrices/5094783540359394322/executions/bs.8552d4b7c4243277/testcases/2
### Stacktrace:
```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at org.mozilla.samples.glean.MainActivityTest.checkGleanClickData(MainActivityTest.kt:48)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:154)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837)
```
### Build: 
https://github.com/mozilla-mobile/android-components/commit/92125ff1b10e948530562b5dbba99f1241db8992

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17529)

**Comment by AaronMT** [comment] 2021-11-30 14:56
This appeared yesterday https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/P4HoE-wlTxGI-U0QzpM9UQ/runs/0/artifacts/public/logs/live_backing.log from https://github.com/mozilla-mobile/android-components/pull/11324

**Comment by sv-ohorvath** [comment] 2022-01-14 14:40
Failed with a crash on Nexus 6, on 1/14/22: https://console.firebase.google.com/project/moz-android-components-230120/testlab/histories/bh.acacddb44ee28c64/matrices/6186708473554195496/executions/bs.4bd04668e6fcf414

**Comment by sv-ohorvath** [comment] 2022-05-27 14:07
Failed on 5/27:
https://console.firebase.google.com/project/moz-android-components-230120/testlab/histories/bh.acacddb44ee28c64/matrices/7644977900936372041/details?stepId=bs.920b0f6d5fb6164e&testCaseId=2
`java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at org.mozilla.samples.glean.MainActivityTest.checkGleanClickData(MainActivityTest.kt:48)`

**Comment by csadilek** [comment] 2022-10-12 18:31
Dupe of https://github.com/mozilla-mobile/android-components/issues/12311.

**Closed by csadilek** 2022-10-12 18:31 UTC
Labels: 🎲 intermittent-test
