### ISSUE TITLE
[intermittent] feature-custom-tabs: close button invokes callback and removes session

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#10809] opened 2021-08-13 16:22 UTC
Happened in: https://github.com/mozilla-mobile/android-components/pull/10800

```
[task 2021-08-12T22:48:49.692Z] 	at mozilla.components.support.test.middleware.CaptureActionsMiddleware.assertLastAction(CaptureActionsMiddleware.kt:64)
[task 2021-08-12T22:48:49.692Z] 	at mozilla.components.feature.customtabs.CustomTabsToolbarFeatureTest.close button invokes callback and removes session(CustomTabsToolbarFeatureTest.kt:288)
[task 2021-08-12T22:48:49.692Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2021-08-12T22:48:49.693Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2021-08-12T22:48:49.693Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2021-08-12T22:48:49.693Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[task 2021-08-12T22:48:49.693Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2021-08-12T22:48:49.693Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2021-08-12T22:48:49.693Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2021-08-12T22:48:49.693Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2021-08-12T22:48:49.693Z] 	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:601)
[task 2021-08-12T22:48:49.693Z] 	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:260)
[task 2021-08-12T22:48:49.693Z] 	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
[task 2021-08-12T22:48:49.693Z] 	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
[task 2021-08-12T22:48:49.693Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[task 2021-08-12T22:48:49.693Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[task 2021-08-12T22:48:49.693Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[task 2021-08-12T22:48:49.693Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[task 2021-08-12T22:48:49.693Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[task 2021-08-12T22:48:49.693Z] 	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
[task 2021-08-12T22:48:49.693Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[task 2021-08-12T22:48:49.693Z] 	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:154)
[task 2021-08-12T22:48:49.693Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
[task 2021-08-12T22:48:49.693Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
[task 2021-08-12T22:48:49.693Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
[task 2021-08-12T22:48:49.693Z] 	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[task 2021-08-12T22:48:49.693Z] 	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
[task 2021-08-12T22:48:49.693Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2021-08-12T22:48:49.693Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2021-08-12T22:48:49.694Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2021-08-12T22:48:49.694Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[task 2021-08-12T22:48:49.694Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2021-08-12T22:48:49.694Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2021-08-12T22:48:49.694Z] 	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
[task 2021-08-12T22:48:49.694Z] 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
[task 2021-08-12T22:48:49.694Z] 	at com.sun.proxy.$Proxy5.processTestClass(Unknown Source)
[task 2021-08-12T22:48:49.694Z] 	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:121)
[task 2021-08-12T22:48:49.694Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2021-08-12T22:48:49.694Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2021-08-12T22:48:49.694Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2021-08-12T22:48:49.694Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[task 2021-08-12T22:48:49.694Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2021-08-12T22:48:49.694Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2021-08-12T22:48:49.694Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
[task 2021-08-12T22:48:49.694Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
[task 2021-08-12T22:48:49.694Z] 	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
[task 2021-08-12T22:48:49.694Z] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[task 2021-08-12T22:48:49.694Z] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[task 2021-08-12T22:48:49.694Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[task 2021-08-12T22:48:49.694Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[task 2021-08-12T22:48:49.694Z] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
[task 2021-08-12T22:48:49.694Z] 	at java.base/java.lang.Thread.run(Thread.java:829)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17586)

**Comment by csadilek** [comment] 2022-10-12 22:31
Dupe of https://github.com/mozilla-mobile/android-components/issues/11342.

**Closed by csadilek** 2022-10-12 22:31 UTC
Labels: ✅ testing, <customtabs>, 🎲 intermittent-test
