### ISSUE TITLE
Fennec migration: The user is not kept logged in

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/android-components#5551] opened 2020-01-13 13:10 UTC
## Preconditions:
Have Fennec installed and logged in.
## Steps to reproduce
1. Replace Fennec with Fenix using a build from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration;
2. Launch Fenix;
3. Go to Settings;
4. Observe the logged in state;
### Expected behavior
The user is logged in.
### Actual behavior
The user is not kept logged in, "Turn on Sync" is displayed.

### Device information

* Android device: Samsung Galaxy S8 (Android 9), Huawei Honor 8 (Android 7.0), Xiaomi Mi4i (Android 5.0.2)
* Fenix version: Release, Beta, Nightly migration builds 01/13

**Comment by grigoryk** [comment] 2020-01-14 03:36
Yup, this does indeed happen for me locally. Most likely to do with the changes in 0.48.1 and https://github.com/mozilla-mobile/android-components/pull/5500 (since nothing here changed recently)...

```
01-13 19:34:04.170  7259  7397 E FennecMigrator: mozilla.components.support.migration.FxaMigrationException: Failed to sign-into authenticated account in state Married
01-13 19:34:04.170  7259  7397 E FennecMigrator: 	at mozilla.components.support.migration.AuthenticatedAccountProcessor.signIn$support_migration_release(FennecFxaMigration.kt:22)
01-13 19:34:04.170  7259  7397 E FennecMigrator: 	at mozilla.components.support.migration.AuthenticatedAccountProcessor$signIn$1.invokeSuspend(Unknown Source:12)
01-13 19:34:04.170  7259  7397 E FennecMigrator: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
01-13 19:34:04.170  7259  7397 E FennecMigrator: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
01-13 19:34:04.170  7259  7397 E FennecMigrator: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-13 19:34:04.170  7259  7397 E FennecMigrator: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-13 19:34:04.170  7259  7397 E FennecMigrator: 	at java.lang.Thread.run(Thread.java:919)
```

```
01-13 19:34:04.171  7259  7259 D MigrationService: Migration completed:
01-13 19:34:04.171  7259  7259 D MigrationService: mozilla.components.support.migration.Migration$Settings@e61e329, version=1 success=true
01-13 19:34:04.171  7259  7259 D MigrationService: mozilla.components.support.migration.Migration$OpenTabs@d9a66ae, version=1 success=true
01-13 19:34:04.171  7259  7259 D MigrationService: mozilla.components.support.migration.Migration$History@e9aec4f, version=1 success=true
01-13 19:34:04.171  7259  7259 D MigrationService: mozilla.components.support.migration.Migration$Bookmarks@10dfdc, version=1 success=true
01-13 19:34:04.171  7259  7259 D MigrationService: mozilla.components.support.migration.Migration$Logins@b8c88e5, version=1 success=true
01-13 19:34:04.172  7259  7259 D MigrationService: mozilla.components.support.migration.Migration$FxA@2aa3fba, version=1 success=false
```

**Comment by rfk** [comment] 2020-01-14 06:37
I think I managed to reproduce this locally, although it took me several tries. I see the following logcat output:

```
01-14 17:20:53.435 21656 21709 W fxa_client::ffi: Remote server error: '400' '124' 'Bad Request' 'Session already registered by another device' 'https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/docs/api.md#response-format')^M
01-14 17:20:53.465 21656 21709 E FirefoxAccount: Error while running: migrateFromSessionToken^M
01-14 17:20:53.465 21656 21709 E FirefoxAccount: mozilla.appservices.fxaclient.FxaException$Unspecified: Remote server error: '400' '124' 'Bad Request' 'Session already registered by another device' 'https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/docs/api.md#response-format'^M
01-14 17:20:53.465 21656 21709 E FirefoxAccount:        at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:48)^M
01-14 17:20:53.465 21656 21709 E FirefoxAccount:        at mozilla.appservices.fxaclient.FirefoxAccount.migrateFromSessionToken(FirefoxAccount.kt:795)^M
01-14 17:20:53.465 21656 21709 E FirefoxAccount:        at mozilla.components.service.fxa.FirefoxAccount$migrateFromSessionTokenAsync$1$1.invoke(FirefoxAccount.kt:159)^M
01-14 17:20:53.465 21656 21709 E FirefoxAccount:        at mozilla.components.service.fxa.FirefoxAccount$migrateFromSessionTokenAsync$1$1.invoke(FirefoxAccount.kt:27)^M
01-14 17:20:53.465 21656 21709 E FirefoxAccount:        at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$7.invokeSuspend(Utils.kt:68)^M
01-14 17:20:53.465 21656 21709 E FirefoxAccount:        at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$7.invoke(Utils.kt)^M
01-14 17:20:53.465 21656 21709 E FirefoxAccount:        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:28)^M
01-14 17:20:53.465 21656 21709 E FirefoxAccount:        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:60)^M
01-14 17:20:53.465 21656 21709 E FirefoxAccount:        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:67)^M
01-14 17:20:53.465 21656 21709 E FirefoxAccount:        at mozilla.components.service.fxa.FirefoxAccount$migrateFromSessionTokenAsync$1.invokeSuspend(FirefoxAccount.kt:158)^M
01-14 17:20:53.465 21656 21709 E FirefoxAccount:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)^M
01-14 17:20:53.465 21656 21709 E FirefoxAccount:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)^M
01-14 17:20:53.465 21656 21709 E FirefoxAccount:        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)^M
01-14 17:20:53.465 21656 21709 E FirefoxAccount:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)^M
01-14 17:20:53.465 21656 21709 E FirefoxAccount:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)^M
01-14 17:20:53.465 21656 21709 E FirefoxAccount:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)^M
01-14 17:20:53.465 21656 21842 E FennecMigrator: Failed to sign-in into an authenticated account^M
01-14 17:20:53.465 21656 21842 I mozac/CrashReporter: Caught Exception report submitted to 2 services^M
```

**Comment by rfk** [comment] 2020-01-14 07:27
So here's what I think is happening, with a warning that it gets really into the FxA weeds really fast:

* Fenix successfully reads the FxA `sessionToken` from the previous account state. Since that `sessionToken` was previously owned by Fennec, it has an associated FxA device record.
* It uses that `sessionToken` to authorize itself some OAuth tokens. Since there is an existing FxA device record, the OAuth refresh token gets associated with it.
* Fenix sees that it successfully got some tokens, and pumps its FxA state machine to a stable state. As part of this process it tries to initialize a new device record, since as far as it's concerned the user has just done a fresh login.
* The FxA server sees a request to create a new device record coming from a token that is already associated with an existing device record, and it throws the above error.

I don't fully understand why that last step happens, because there *is* some logic in the FxA server that's supposed to handle transparently AFAICT. I'll keep digging.

As a short-term fix, I think we need to revert to the previous behaviour of *duplicating* the `sessionToken` rather than taking ownership of it. The user will end up with an abandoned "Firefox for Android" entry in their FxA device list, but as least they won't get logged out during the upgrade. That should get this working again for the Nightly migration, and we can figure out how to do the smoother taking-over-the-same-token experience properly for Beta.

Changing the FxA migration to set [`reuseAccount=False`](https://github.com/mozilla-mobile/android-components/blob/9aa23e07f5fc932bb3b5a833c7026bbfeedce7ef/components/support/migration/src/main/java/mozilla/components/support/migration/FennecFxaMigration.kt#L139) should get things back up and running here, although I'm out of time to test that for today.

**Comment by rfk** [comment] 2020-01-14 07:41
I filed https://github.com/mozilla/application-services/issues/2473 to dig in and figure out a proper fix rather than the `reuseAccount=False` workaround.

**Comment by vladikoff** [comment] 2020-01-14 20:37
> Changing the FxA migration to set reuseAccount=False

Could we please do that ASAP? PR in https://github.com/mozilla-mobile/android-components/pull/5571 cc @grigoryk

**Comment by ebalazs-sv** [comment] 2020-01-15 14:26
This is still reproducible on today's migration builds 01/15, I will test this again on the next builds.

**Comment by grigoryk** [comment] 2020-01-16 19:18
As far as we know, this works in the latest builds.

**Comment by ebalazs-sv** [comment] 2020-01-17 08:14
Verified as fixed on Fennec Migration Nightly build 1 with Samsung Galaxy S8 (Android 9) - ARM64, Xiaomi Mi Pad 2 (Android 5.1) - x86, OnePlus 6T (Android 9.0) - ARM. The user is kept logged in after the migration.
I will move this to Done. Thanks!

**Comment by st3fan** [comment] 2020-02-18 01:13
Closing since this is Verified as Fixed.

**Closed by st3fan** 2020-02-18 01:13 UTC
Labels: <migration>, 🐞 bug

**Comment by ebalazs-sv** [comment] 2020-02-18 07:10
This was verified as fixed so I will move it to Done.
