### ISSUE TITLE
Fennec migration: Open tabs are displayed in the list only after dismissing the homescreen

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/android-components#5305] opened 2019-12-13 13:02 UTC
## Preconditions:
Have open tabs on Fennec.
## Steps to reproduce
1. Replace Fennec with Fenix using a build from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration;
2. Launch Fenix and tap Start browsing;
3. Observe the Open tabs from homescreen.
### Expected behavior
The open tabs are displayed.
### Actual behavior
The open tabs are displayed only after dismissing the homescreen by going to Settings/ Recent apps.
### Notes:
[Video](https://drive.google.com/file/d/1hJdwxGbmnBNocJYhg0O928ngGgFu-BSs/view?usp=sharing)
### Device information

* Android device:  Pixel 3a XL (Android 10), Samsung Galaxy S8 (Android 9) - ARM64; Huawei Honor 8 (Android 7.0).
* Fenix version: Release, Beta, Nightly 12/13.

**Comment by pocmo** [comment] 2020-01-16 08:53
We had hoped that would be fixed after introducing the migration UI since then the tabs would already be in `SessionManager` once we launch the home screen. However this doesn't seem to be the case. I just tested the first nightly build and I was able to still reproduce this.

**Comment by abodea** [comment] 2020-01-16 10:49
Still reproducible on the 1/16 build.

**Comment by pocmo** [comment] 2020-01-16 12:24
This somehow seems to be caused by the onboarding screen showing up first. If onboarding is disabled then tabs appear immediately. 🤔

**Comment by pocmo** [comment] 2020-01-16 17:48
Fixed with the next build.

**Closed by pocmo** 2020-01-16 17:48 UTC
Labels: <migration>, 🐞 bug

**Comment by ebalazs-sv** [comment] 2020-01-17 12:23
Verified as fixed on Fennec Nightly migration build 2, 01/17 with Samsung Galaxy S8 (Android 9) - ARM64, Xiaomi Mi Pad 2 (Android 5.1) - x86, Huawei MediaPad M3 Lite 10 (Android 7.0) - ARM.
I will move this to Done. Thanks!
