### ISSUE TITLE
Synced tabs from Fenix never have an icon

### ISSUE THREAD

**Issue by mhammond** [mozilla-mobile/android-components#12360] opened 2022-06-21 00:42 UTC
via [bug 1774202](https://bugzilla.mozilla.org/show_bug.cgi?id=1774202) - It looks like [there's an attempt to supply one](https://github.com/mozilla-mobile/android-components/blob/aeb97b1cb5ff38d564a911501ad2f43abcda27e4/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/RemoteTabsStorage.kt#L51), but I've never actually seen one. When the tab is shown on desktop and no tab is supplied, desktop itself tries to find one, so this isn't immediately obvious.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20760)

**Comment by jonalmeida** [comment] 2022-06-23 18:26
Ah, I see that the new designs are already in Beta for me. So they should make their way to Release if they haven't reach there yet.

**Comment by mhammond** [comment] 2022-06-24 00:10
Note that this bug is not about showing icon on Fenix, it's about Fenix not supplying the icon when supplying synced tabs for use by other devices. IOW, *desktop* can't see what icon to use for tabs opened on a Fenix installation. (Desktop does try to use a fallback, so it's not particularly obvious)

To reproduce: use, [about-sync](https://addons.mozilla.org/en-US/firefox/addon/about-sync/) on desktop, look for the tabs listed for the Fenix device, and every record has `null` for `icon`

**Comment by jonalmeida** [comment] 2022-06-28 20:35
Sorry, I misread.

This is then a duplicate of https://github.com/mozilla-mobile/android-components/issues/5179.

**Comment by jonalmeida** [comment] 2022-10-08 02:46
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794228

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by jonalmeida** 2022-10-08 02:46 UTC
Labels: <sync-tabs>
