### ISSUE TITLE
Horizontal Swiping Triggers Toolbar Hide/Show behavior 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#2695] opened 2019-04-09 21:51 UTC
STR: 
Scroll through carousel on a page like https://www.cnn.com/2019/04/09/tech/locked-ipad-boy-trnd/index.html

Expected: 
Toolbar only reacts to vertical scrollings

Actual:
Toolbar shows/hides and reacts to horizontal scroll

**Comment by jonalmeida** [comment] 2019-04-20 21:20
Related: https://github.com/mozilla-mobile/reference-browser/issues/617

**Comment by sblatz** [comment] 2020-01-06 18:17
Sounds like we need GV for this. @jonalmeida  will be filing 😄

**Comment by jonalmeida** [comment] 2020-01-09 01:07
Firstly, we definitely don't need to work on this now since we disable the toolbar from scrolling.

Looking at the [`ScrollDelegate.onScrollChanged`](https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoSession.ScrollDelegate.html#onScrollChanged-org.mozilla.geckoview.GeckoSession-int-int-), I think we have the information we need to know when the scroll position is changing in web content so that we can disable the BrowserToolbarBottomBehavior when needed. From the [r-b bug](https://github.com/mozilla-mobile/reference-browser/issues/617#issuecomment-465481722), we probably need to find the right thresholds that we want.

**Comment by jonalmeida** [comment] 2020-01-09 01:08
Leaving this to @sblatz to figure out why this is a top 10 A-C bug when the behaviour is disabled.

**Comment by ekager** [comment] 2020-01-09 05:04
We have the hiding top toolbar as an option again in Fenix now and this bug is less noticeable but still exists there as well

**Comment by jonalmeida** [comment] 2020-01-09 05:51
Ah, interesting. It seems like Fenix uses a custom bottom and top toolbar behaviour right now, but regardless, we probably need to build an API similar to the one [SwipeRefreshFeature](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/session/src/main/java/mozilla/components/feature/session/SwipeRefreshFeature.kt) uses for knowing the scroll-ability of web content.

But yeah, this doesn't sound like it's a top bug to work on right now since it doesn't have a priority.

**Comment by sblatz** [comment] 2020-03-30 17:24
@pocmo please confirm this also fixes https://github.com/mozilla-mobile/fenix/issues/2278

**Comment by Mugurell** [comment] 2020-04-07 15:26
This issue seems to only be happening in carousels / iframes and not in plain websites.

Currently GV's PZC returns `INPUT_RESULT_HANDLED` for inner scrolls also (like in the case described here) [based on which we will indeed](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBottomBehavior.kt#L68) scroll the navbar.

I think this will be automagically fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1627737 which will return `INPUT_RESULT_HANDLED_CONTENT` for scrolls inside iframes / scrollable divs so I propose waiting for this change to see if there will be anything left to do in A-C.

**Comment by pocmo** [comment] 2020-04-09 11:44
Moving this out of our sprint back into the triage column so that we can get back to it.

**Comment by sblatz** [comment] 2020-04-27 22:54
Putting this back in top 10 since it doesn't look like we have traction on it :)

**Comment by Mugurell** [comment] 2020-05-04 09:56
PR https://github.com/mozilla-mobile/android-components/pull/6666 should also fix this.

**Comment by Mugurell** [comment] 2020-05-12 13:38
The above patches were merged.
Planning to go through all Fenix / RB issues with the help of QA to verify problems as this does not reproduce anymore.

**Comment by Mugurell** [comment] 2020-05-19 09:26
Seems like this this flow is working nicely now
![HorizontalScrollsDontAnimateTool](https://user-images.githubusercontent.com/11428869/82309492-e05fb180-99cb-11ea-8cd5-2b2d571e2f85.gif)

There are still some issues with the urlBar for when placed at top for which I've created https://github.com/mozilla-mobile/fenix/issues/10686 on Fenix to discuss the best approach on fixing the remaining but seems like this is now working as expected.

**Closed by Mugurell** 2020-05-19 09:26 UTC
Labels: <toolbar>, 🌐 reference browser, 🐉 Fenix, 🐞 bug
