### ISSUE TITLE
Update "Not yet available" copy

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/android-components#6287] opened 2020-03-16 22:34 UTC
The following copy needs to be updated. @betsymi has the correct copy. 

![Screenshot_20200313-143124_Firefox_Nightly](https://user-images.githubusercontent.com/42752644/76805261-bfed5e00-67b4-11ea-899a-5c01e3e4e1af.png)

**Comment by vesta0** [comment] 2020-03-17 20:47
@betsymi I copied your feedback here:

### Not yet available

We're currently building support for an initial selection of Recommended Extensions. [Learn more](https://support.mozilla.org/en-US/kb/add-compatibility-firefox-preview)

Other UX notes, paging @brampitoyo so he's aware. 

- Remove trash can icon
- Can the [Learn more](https://support.mozilla.org/en-US/kb/add-compatibility-firefox-preview) go immediately after the line of copy? This would tighten things up.

**Comment by ebalazs-sv** [comment] 2020-04-01 09:14
I tested this on 
- Release Migration build 4.0.0-beta.2 (Build #2015731955), GV 75, 4/1;
- Nightly migration build 200401 (Build #2015731955), GV 76, 4/1 

with 
- Google Pixel 2 (Android 9);
- Motorola Moto G6 (Android 8), 

and it is not updated to "Not yet available". The title is still "Not yet supported".
[Screenshot](https://drive.google.com/open?id=1ga2GUIu-wVbq8xasJrBPL-Bn1GAuay7b)
@psymoon I will reopen this issue due to the issue described above.

**Comment by pocmo** [comment] 2020-04-01 10:48
This fix will be available in 75 beta 3.

**Comment by psymoon** [comment] 2020-04-01 14:17
I think the title still needs toc

> I tested this on
> 
>     * Release Migration build 4.0.0-beta.2 (Build #2015731955), GV 75, 4/1;
> 
>     * Nightly migration build 200401 (Build #2015731955), GV 76, 4/1
> 
> 
> with
> 
>     * Google Pixel 2 (Android 9);
> 
>     * Motorola Moto G6 (Android 8),
> 
> 
> and it is not updated to "Not yet available". The title is still "Not yet supported".
> [Screenshot](https://drive.google.com/open?id=1ga2GUIu-wVbq8xasJrBPL-Bn1GAuay7b)
> @psymoon I will reopen this issue due to the issue described above.

@ebalazs-sv @pocmo I forgot to change the title, I will update this.

**Comment by ebalazs-sv** [comment] 2020-04-02 09:01
This is reproducible on Beta Migration build 75.0.0-beta.3 4/2 with Samsung Galaxy Tab S6 (Android 9) and Huawei P9 Lite (Android 7).
The copy is not updated.
The same copy as in https://github.com/mozilla-mobile/android-components/issues/6287#issue-582637511 is displayed.
Due to that, I will move this from Ready for QA to Beta.

**Comment by ebalazs-sv** [comment] 2020-04-03 09:09
@psymoon I tested this on the Nightly Migration 200403 (Build #2015732339) 4/3 with Pixel 2 (Android 9) and the "Not yet supported" title is still displayed after opening the "Not yet available" section.
[Video](https://drive.google.com/open?id=1w5ctTO6WagvDpMCn0CKimOf2dBAqwPrP)
Due to that I will reopen this issue.

**Comment by ebalazs-sv** [comment] 2020-04-15 11:08
This is reproducible on Beta Migration build 75.0.0-beta.5, from 4/14, with Huawei P9 Lite (Android 7).

**Comment by st3fan** [comment] 2020-04-30 16:43
@ebalazs-sv Can this one be verified on Firefox Preview 5.0 and the latest migration build?

**Comment by ebalazs-sv** [comment] 2020-05-04 12:36
Verified as fixed on the latest Beta Migration Build 76.0.0-beta.1 with Nexus 5 (Android 6.0.1) and Motorola Moto G6 (Android 8).
The "Not yet available" section is displayed at the end of the Add-ons list, with the copy from https://github.com/mozilla-mobile/android-components/issues/6287#issuecomment-600289219.

**Closed** 2020-05-06 17:41 UTC
Labels: <web-extensions>, E3, 🐉 Fenix

**Comment by ebalazs-sv** [comment] 2020-05-07 07:20
This issue was verified as fixed, see details in https://github.com/mozilla-mobile/android-components/issues/6287#issuecomment-623437704, so I will move it to Done. Thanks!
