### ISSUE TITLE
push::crypto - base64 failed for target:dh; InvalidLength

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#7315] opened 2020-06-09 21:42 UTC
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/8679281/events/4d357aa35f8e4f568ef2d5ad72222d9f/

```
....
    at $Proxy5.push_decrypt
    at mozilla.appservices.push.PushManager.decrypt(PushManager.kt:5)
    at mozilla.components.feature.push.RustPushConnection.decryptMessage(Connection.kt:5)
    at mozilla.components.feature.push.AutoPushFeature$onMessageReceived$$inlined$ifInitialized$lambda$1.invokeSuspend(AutoPushFeature.kt:12)
    at mozilla.components.feature.push.AutoPushFeature$onMessageReceived$$inlined$ifInitialized$lambda$1.invoke
    at mozilla.components.feature.push.ext.CoroutineScopeKt$launchAndTry$2.invokeSuspend(CoroutineScope.kt:5)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)
```

**Comment by jonalmeida** [comment] 2020-07-21 16:46
Closing this as a duplicate of issue https://github.com/mozilla-mobile/android-components/issues/7316 as mentioned in the a-s bug: https://github.com/mozilla/application-services/issues/3364#issuecomment-660797067

**Closed by jonalmeida** 2020-07-21 16:46 UTC
Labels: <push>, a-s, 🐞 bug
