### ISSUE TITLE
SmokeTests: Assertion error

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6482] opened 2020-04-01 10:05 UTC
After fixing the leak our smoke tests for the sample browser pass. But they still seem to fail on API 21 for some kind of reason (https://github.com/mozilla-mobile/android-components/pull/6279):

```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at org.mozilla.samples.browser.SmokeTestsKt.verifyWebsiteContent(SmokeTests.kt:128)
at org.mozilla.samples.browser.SmokeTestsKt.access$verifyWebsiteContent(SmokeTests.kt:1)
at org.mozilla.samples.browser.SmokeTests.loadWebsitesInMultipleTabsTest(SmokeTests.kt:68)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at mozilla.components.support.android.test.leaks.LeakDetectionRule$apply$1.evaluate(LeakDetectionRule.kt:44)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837)
```

**Comment by pocmo** [comment] 2020-04-01 10:11
Since this is failing when trying to verify the web content, I wonder if this is a limitation in GeckoView on API 21? @snorp Do you know?

@isabelrios I saw that we run Fenix tests on API 27 and 28 only. And for RB tests only on API 25 and 28. Can we exclude API 21 here for now until we know what is causing this?

**Comment by isabelrios** [comment] 2020-04-01 11:20
> @isabelrios I saw that we run Fenix tests on API 27 and 28 only. And for RB tests only on API 25 and 28. Can we exclude API 21 here for now until we know what is causing this?

Yeah, I think that's doable, thanks!

**Comment by snorp** [comment] 2020-04-01 14:22
I guess it's possible? Does UIAutomator use a11y to inspect the GeckoView? I could see us having a problem there with some API versions, but I would expect it to work on 21. Maybe @eeejay can help us here.

**Comment by Archaeopteryx** [comment] 2020-08-07 11:49
Looks like a regression from #6813 and fails ~50% of the runs. @pocmo can you take a look?

**Comment by grigoryk** [comment] 2020-08-19 22:46
Just saw this failure on a `release/54.0` branch. Video from the test run shows that we ended up on the Google search page. In the test, the search suggestion somehow got clicked on.

Google search page definitely didn't have the `Hello World` string that the text is trying to verify.

**Comment by Archaeopteryx** [comment] 2020-12-04 11:28
@eliserichards @pocmo This started to fail permanently when #2743 got [merged](https://treeherder.mozilla.org/jobs?repo=android-components&group_state=expanded&resultStatus=testfailed%2Cbusted%2Cexception%2Cusercancel%2Crunnable&selectedTaskRun=UUdL-SchRMm6Gkn5aBjqXw.0).

**Comment by csadilek** [comment] 2020-12-04 14:54
I will take look, I think it's just the view ID that changed.

**Comment by csadilek** [comment] 2020-12-04 15:34
PR to fix tests: https://github.com/mozilla-mobile/android-components/pull/9137 (we just dropped the content description the tests uses to look up the counter/button).

**Closed** 2020-12-08 08:58 UTC
Labels: :iphone: sample, ✅ testing
