### ISSUE TITLE
Only remove thumbnails after session undo is dismissed

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/android-components#7479] opened 2020-06-24 02:46 UTC
In #7185, we remove thumbnails after the session is removed. In #3265, we will look to support undo, so we should find a way to hook this up with dismissing a session undo.

**Comment by jonalmeida** [comment] 2021-04-13 02:40
Duplicate of https://github.com/mozilla-mobile/android-components/issues/8395

**Closed by jonalmeida** 2021-04-13 02:40 UTC
Labels: <thumbnails>, blocked
