### ISSUE TITLE
Content fixed to the bottom of the screen is behind the URL bar

### ISSUE THREAD

**Issue by theres-waldo** [mozilla-mobile/android-components#4536] opened 2019-09-25 22:35 UTC
**Steps to reproduce**

* Run either Reference Browser, or Fenix with [this patch](https://github.com/csadilek/fenix/commit/b48310092ac7a56ab51930356879929fdb024444) applied to enable the dynamic toolbar (URL bar that hides when you scroll).
* Load https://www.sozone.de/.

**Expected results**

The page's green bottom bar (cookie banner) is just above the URL bar.

**Actual results**

The page's green bottom bar (cookie banner) is behind the URL bar.

This is a regression since the time [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1552608) was filed in May.

At the implementation level, it looks like GeckoView's `setVerticalClipping` API, which was added in [bug 1516048](https://bugzilla.mozilla.org/show_bug.cgi?id=1516048) and is supposed to adjust the position of bottom-fixed content, is not being called.

As the issue is common to Fenix and R-B, I assume it's an issue in Android Components.

cc @csadilek @pocmo @snorp

**Comment by hiikezoe** [comment] 2019-09-30 08:59
As for reference browser, mozilla-mobile/reference-browser@f37af24422c5fb146 regressed this.

**Comment by hiikezoe** [comment] 2019-10-01 00:42
FWW, hiikezoe/reference-browser@e9cec7a7 is a fix to call setVerticalClipping properly.  Maybe it's not perfect but it's sufficient for me to figure out ways to fix [bug 1515980](https://bugzilla.mozilla.org/show_bug.cgi?id=1515980).
One thing I am still wondering is that using CoordinatorLayout is the way we make the toolbar dynamic in future?  I suppose it is since [Chrome also uses it](https://cs.chromium.org/chromium/src/chrome/android/java/res/layout/main.xml?l=10&rcl=aaa67b1e861b1c47a48e21af124c3c64266ace61), though it's actually [slightly modified](https://cs.chromium.org/chromium/src/chrome/android/java/src/org/chromium/chrome/browser/coordinator/CoordinatorLayoutForPointer.java?l=20&rcl=aaa67b1e861b1c47a48e21af124c3c64266ace61).

**Comment by cpeterso** [comment] 2019-10-08 21:50
A fix for the GV bug landed and should be available in tomorrow's GV 71 Nightly.

https://bugzilla.mozilla.org/show_bug.cgi?id=1552608#c47

**Closed** 2019-10-11 15:01 UTC
Labels: <toolbar>, E2, 🐞 bug

**Comment by hiikezoe** [comment] 2019-10-16 23:36
Has someone confirmed that dedb09a fixed the issue for reference-browser?  I still don't see any setVerticalClipping calls there.  IIUC [CoordinatorLayout.Behavior](https://developer.android.com/reference/android/support/design/widget/CoordinatorLayout.Behavior.html#layoutDependsOn(android.support.design.widget.CoordinatorLayout,%20V,%20android.view.View)), layoutDepednsOn is called only for its children, and as far as I can tell, in reference-browser [EngineView is a grand child of the CoordinatorLayout](https://github.com/mozilla-mobile/reference-browser/blob/ae80c2d68557d7f9cb3a54ce8ed25f71d087fbc9/app/src/main/res/layout/fragment_browser.xml#L18-L22), so....

@pocmo are there any trick to make it work for reference browser?

**Comment by hiikezoe** [comment] 2019-10-16 23:45
Anyways, I DO strongly suggest to write _integrated_ automated tests for this functionality, it had been already regressed once as I wrote in the second comment. I understand it's bit unfortunate since the current dynamic toolbar implementation is spread in different repositories.  I don't know reasons why we can't implement it in mozilla-central, but I guess there are some reasons.

@cpeterso do we have plans to run _integrated_ tests on our m-c's CIs with reference-browser or fenix?

**Comment by hiikezoe** [comment] 2019-10-22 23:28
I confirmed this was fixed by https://github.com/mozilla-mobile/reference-browser/commit/9f39d4d7c2db949e35b1fb7094365d7ff3dc27b8 .
