### ISSUE TITLE
KotlinNullPointerException in FxaAccountManager.postAuthenticated

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#7881] opened 2020-07-28 11:55 UTC
> https://sentry.prod.mozaws.net/operations/fenix-fennec/issues/9160982

```
kotlin.KotlinNullPointerException: null
    at kotlin.jvm.internal.ArrayIteratorKt.throwNpe(ArrayIterator.kt:1)
    at mozilla.components.service.fxa.manager.FxaAccountManager.postAuthenticated(FxaAccountManager.kt:30)
    at mozilla.components.service.fxa.manager.FxaAccountManager$postAuthenticated$1.invokeSuspend
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)
```

**Comment by ekager** [comment] 2020-07-28 13:32
See https://github.com/mozilla-mobile/android-components/issues/7536

**Comment by grigoryk** [comment] 2020-07-28 16:46
Yup, that's a dupe of #7536.

**Closed by grigoryk** 2020-07-28 16:46 UTC
Labels: <firefox-accounts>, R79, 🐞 bug
