### ISSUE TITLE
Enhancement - Fennec migration: Add support for Youtube and Reddit (custom search engine)

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/android-components#5829] opened 2020-02-06 10:54 UTC
## Prerequisites
- Change the default search engine on Fennec to Youtube.
- Replace Fennec with Fenix.

## Steps to reproduce
1. Launch Fenix and perform a search.

### Expected behavior
The search is done through Youtube.

### Actual behavior
The search is done through Google.

### Note: 
- Youtube and Reddit are displayed in Fenix settings: Search -> add search engine but are not added in the default list.

### Device information
* Android device:  Motorola Moto G6 (Android 8.0), Xiaomi Mi Pad 2 (Android 5.1) - x86 architecture.
* Fenix version: Nightly migration build 7 - 2/6.

**Comment by pocmo** [comment] 2020-02-06 13:10
That is the intended behavior - see https://github.com/mozilla-mobile/android-components/issues/5818 for details. Right now we do not migrate custom search engines. We only try to find the previous default in the list of search engines in Fenix - if it isn't in that list then we fallback to the default.

**Comment by pocmo** [comment] 2020-02-07 09:56
Closing this for now since that is the expected behavior. However we have telemetry probes to see how many successful/failed migrations of search engines we see and we will monitor those numbers to see whether we should improve the search engine migration.

**Closed by pocmo** 2020-02-07 09:56 UTC
Labels: <migration>
