### ISSUE TITLE
Don't run a CI build on documentation changes

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#783] opened 2018-09-13 16:57 UTC
When we make PRs for documentation/README/changelog changes, we have to wait for a full build to complete until we can merge.

We should consider running either a "sanity" build that does just minimal or simply don't run the build at all.

**Comment by csadilek** [comment] 2018-09-13 18:51
Dupe of #641.

**Closed by csadilek** 2018-09-13 18:51 UTC
Labels: 🏗️ build, 💡idea, 🔬 Research, 🤖 automation
