### ISSUE TITLE
WebNotifications do not invoke any event when clicked

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#7477] opened 2020-06-23 22:51 UTC
From a discussion in Slack, it seems that we may not be handling WebNotifications correctly as expected when clicked.

We should investigate why this is caused and how to fix it.
 - Are we invoking the `onClick`?
 - What does the `onClick` trigger in GV and is it being triggered?

**Comment by kbrosnan** [comment] 2020-10-05 19:43
Seeing a few comments about this being broken and https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/notificationclick_event says we support this event. Can we get this in an upcoming sprint? Do we need GV work to pass the event back to Gecko?

**Comment by jonalmeida** [comment] 2020-10-05 20:34
Yes, we have the GV support. I'll add this to the sprint (or the next one if there isn't space).

**Comment by Offerel** [comment] 2021-03-01 10:16
The last response on this bug is from late last year, a long time ago now. The bug is currently open in Firefox Nightly. Any idea, when we can expect a fix for this?

**Comment by devpato** [comment] 2021-03-28 18:30
Hi I'm experiencing this issue as well. Hope this helps:

[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Go to this demo website to send a push notifications: https://onesignal-fcm-e72c4.web.app/ on your mobile Android phone
2. Click on prompt
3. Go to this website on your computer https://onesignal-fcm-e72c4.web.app/
4. On the website listed above from your computer, click on SEND PUSH. 
5. You should receive notification on your phone
6. If you click on the notification, Firefox opens but it doesn't open the URL that the push notification contains.

### Expected behavior

On push notification clicked, Firefox will open the URL that the push notification contains

### Actual behavior

On push notification clicked, Firefox will  doesn't open the URL that the push notification contains. It works on Firefox for computer but not on mobile. Also, other browsers like Chrome and Brave do have the expected behavior. We have tried with OneSignal and Firebase Cloud Messaging and the bug happens in both Push notifications providers. Based on my research I think it's a bug on Firefox.

### Device information

* Device vendor / model and Android version: Google Pixel 5
* Firefox for Android version: ? 87.0.0-rc-1

**Comment by chrisausat** [comment] 2021-09-29 15:36
I have the problem with ORF.at. When it sends a push message, Firefox Mobile opens. But the page to the push message does not open. On Firefox on Windows 10 it works.

**Comment by Bakso69** [comment] 2021-12-28 13:37
Firefox Mobile 95.2.0 same problem.

**Comment by jkasten2** [comment] 2022-02-11 01:51
Also able to reproduce the issue with the following steps on Firefox 97.1.0 on Android 12 on a Galaxy S21.
1. Open https://tests.peter.sh/push-message-generator/
2. Accept notification permissions
3. Go to https://tests.peter.sh/notification-generator/
4. Press "Display the notification"
5. Close the tab to the site.
6. Tap on the notification
7. Observer nothing happens (FF is closed or in the background it will resume, however it doesn't open the peter.sh site)


On the same device with Chrome the above does correctly open the site again as expected.

**Comment by jonalmeida** [comment] 2022-02-22 17:37
Agi also mentioned we need https://github.com/mozilla-mobile/android-components/issues/10723 to land to properly fix this feature.

**Comment by cpeterso** [comment] 2022-02-22 19:29
The corresponding Jira issue: https://mozilla-hub.atlassian.net/browse/FNXV2-6474

**Comment by jonalmeida** [comment] 2022-03-03 04:12
Cathy and I investigated into this issue and we had some findings that we can share here:

- WebNotifications live on the GeckoRuntime.
- In a GeckoView `WebNotification`, we need to trigger the `dismiss` method. Which we can probably do if we call it inside the AC `WebNotification` class:
    ```kotlin
    fun GeckoViewWebNotification.toWebNotification(): WebNotification {
        return WebNotification(
            title = title,
            // ...
            dismiss: () -> Unit = { this.dismiss() }
        )
    }
    ```
- Since a WebNotification is not attached to a session and can live within the _app_ lifetime, we can probably hold it in the BrowserStore state so that we can call dismiss later. I'm thinking along the lines of the [`PromptRequest`](https://github.com/mozilla-mobile/android-components/blob/main/components/concept/engine/src/main/java/mozilla/components/concept/engine/prompt/PromptRequest.kt) and how it handles dismissal as well.
- What we're not sure about is if the app's memory is reclaimed and the notification is still there, will the lambda invoke correctly? The method itself just calls this code which we _could_ technically do ourselves because they are public classes (but GV wouldn't like that) since the methods are not great for a cold-boot:
    ```kotlin
    GeckoAppShell.onNotificationClose(tag, mCookie)
    ```

**Comment by jonalmeida** [comment] 2022-03-03 04:14
Unassigning myself because @Mugurell has assigned themselves to it on JIRA.

**Comment by csadilek** [comment] 2022-03-07 19:50
See also: https://github.com/mozilla-mobile/fenix/issues/24139

**Comment by Mugurell** [comment] 2022-03-16 15:29
@jonalmeida re: https://github.com/mozilla-mobile/android-components/issues/7477#issuecomment-1057647280

I see the notifications needing to work even if the user closes the application in the meantime (and removes it from task manager). If we'd be to keep the notifications in BrowserState we could also serialize them to disk to be able to restore them when the app restarts.

But I was looking at [what happens when a notification is clicked](https://searchfox.org/mozilla-central/rev/fa69d8b248e6c1df670aa6b019e30ec37e6672be/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/WebNotification.java#148) and saw that we only need two strings. 
Seems like these could be added to the notification intent and use the actual notification to "persist" this data needed to identify what notification the user interacted with and then for gecko to know to which service worker to dispatch those actions.

**Comment by jonalmeida** [comment] 2022-03-16 17:07
@Mugurell that sounds good to me - I was leaning on that direction as well. Maybe on GV, we need a method on the runtime that we can use to consume the click and dismiss notifications (which will call into this GeckoAppShell code). Something like this:

```kotlin
geckoRuntime.webNotificationController.dismissNotification(tag, cookie)
```

Could you file a GV bug please? I can bring this up in triage. 🙂

**Comment by Mugurell** [comment] 2022-03-16 17:53
Created https://bugzilla.mozilla.org/show_bug.cgi?id=1759893

**Comment by Mugurell** [comment] 2022-03-31 10:50
GV changes complete. 🎉

**Comment by TitanNano** [comment] 2022-03-31 14:18
@Mugurell will you make this work with PWAs as well? This was a big annoyance of fennec, notifications would always open the main browser.

**Comment by Mugurell** [comment] 2022-03-31 15:06
> @Mugurell will you make this work with PWAs as well? This was a big annoyance of fennec, notifications would always open the main browser.

Will look into that, thank you for raising this.

**Comment by Mugurell** [comment] 2022-04-08 10:08
> @Mugurell will you make this work with PWAs as well? This was a big annoyance of fennec, notifications would always open the main browser.

Supporting this seems to be not so straight-forward.
Opened https://github.com/mozilla-mobile/android-components/issues/11975 to investigate possible approaches.

**Comment by Mugurell** [comment] 2022-04-19 09:43
This functionality was verified in https://github.com/mozilla-mobile/fenix/issues/24618#issuecomment-1101576771.
Closing.

**Closed by Mugurell** 2022-04-19 09:43 UTC
Labels: 🐞 bug, <webnotifications>, S2
