### ISSUE TITLE
Add support for window requests to engine-gecko

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#1503] opened 2018-11-28 16:13 UTC
We now have the API and the implementation for engine-system (added by https://github.com/mozilla-mobile/android-components/pull/1495).

For GeckoView, we're waiting for https://bugzilla.mozilla.org/show_bug.cgi?id=1510314. Once that's resolved, we can send `onOpenWindowRequest` / `onCloseWindowRequest` notifications from engine-gecko.

We also need to make a decision which setting to use enable/disable popup blocking (e.g. `javascriptCanOpenWindowsAutomatically`).

**Comment by csadilek** [comment] 2019-06-05 20:04
@vesta0 @bifleming this is marked as "MVP Blocker` but the feature in Fenix isn't: https://github.com/mozilla-mobile/fenix/issues/1486

Should the label be removed (or added in Fenix)?

We're also blocked on GV for this one. So, if this is a blocker we're cutting it pretty close now as this will still require A-C work.

**Comment by vesta0** [comment] 2019-06-05 20:07
Thanks for calling that out @csadilek 

The reason the Fenix issue wasn't marked as MVP blocker is because we weren't counting on being able to unblock it before MVP which I think you also confirmed. It is still definitely a P1.

**Comment by csadilek** [comment] 2019-07-25 18:27
Removed blocked label, as the fix landed in GV. @cpeterso asked if we could test/verify and since this needs a bit of work in A-C, I added this to the backlog to try out. Maybe we can land this soon and test out in R-B.

**Closed** 2019-07-30 17:49 UTC
Labels: <engine-gecko>, P1, 🌟 feature, 🛑 blocked, 🦎 needs GeckoView API

**Comment by cpeterso** [comment] 2019-08-14 22:47
snorp gave his OK to uplift the GV fix to GV 69 Beta. @csadilek manually verified the GV fix using R-B and GV 70 Nightly. I've requested uplift here: https://bugzilla.mozilla.org/show_bug.cgi?id=1510314#c22
