### ISSUE TITLE
"Debug helper" for the components ecosystem

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#455] opened 2018-07-19 16:35 UTC
In our apps we have the need to have some "debug UI" for QA purposes and debugging.

For example when using the A/B testing framework we want to manually turn on certain experiments. Or when using Mentat we may want to able to look into the database for debugging purposes.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3853)

**Comment by pocmo** [comment] 2018-07-19 16:36
Some options:

* Stetho: https://facebook.github.io/stetho/
* AS plugins?
* Debug Drawer: https://github.com/palaima/DebugDrawer

**Comment by ncalexan** [comment] 2018-07-21 00:06
I looked into Stetho and Debug Drawer more deeply.

- Debug Drawer is intended to be extended with small, independent pieces of functionality.  It's got a rich ecosystem around it.  I think its sweet spot is QA (and intrepid users) digging into specific problems, and developers debugging features that they are not necessarily building.  I don't think it is a great fit for iterating on a specific feature as a developer.

- Stetho is intended to allow deep dives into application internals.  I think its sweet spot is for developers iterating on specific features; requiring a remote device to connect Chrome devtools doesn't sound very QA friendly to me.  (And even less friendly to intrepid users.)  That is, if you would struggle to get logs off an Android device, Stetho won't make that much easier.  Stetho does have a "dumpapp" extension point which might make it easier to get App-specific logs off a device.  I see this dumpapp mechanism as being similar to DebugDrawer, but without the on-device UI.  dumpapp has a WebSocket-y CLI and a bunch of default functioning (fetching files, fetching crashes) which might be really nice.  It's not clear if dumpapp is (easily) accessible from the Chrome devtools interface.

For a specific (common) use case, logging, DebugDrawer includes a Timber drawer that lets you view and send logs, but it's pretty basic -- only a ring buffer of 200 logs is kept.  Stetho includes a Timber logger that just sends everything back to the Chrome devtools console.  Neither of these are really what I, Mentat developer, want: a switch for users and developers to produce detailed logs for just the Mentat bits and get them back to me.

My read on this is that Stetho is more likely to provide immediate value during debugging.  I'll take a pass at exposing Mentat queries and transactions to the existing infrastructure, which makes this look possible.

@colintheshots care to add your impressions?

**Comment by pocmo** [comment] 2018-07-23 08:45
> a switch for users and developers to produce detailed logs for just the Mentat bits and get them back to me.

Can you elaborate a bit more? Your main interest is "just" being able to read the log - or are there more things you want to do?

I think for us in the components world an "in-app" solution would be preferred:
* Turning on/off A/B tests for the installation
* Seeing the internal state of certain components (e.g. SessionManager)
* ..

**Comment by ncalexan** [comment] 2018-07-23 16:48
> a switch for users and developers to produce detailed logs for just the Mentat bits and get them back to me.
> 
> Can you elaborate a bit more? Your main interest is "just" being able to read the log - or are there more things you want to do?
> 
> I think for us in the components world an "in-app" solution would be preferred:
> 
>     Turning on/off A/B tests for the installation
>     Seeing the internal state of certain components (e.g. SessionManager)

There are lots of things I'd like to do:

- export the entire DB
- produce statistics about the whole DB
- expose recent queries and performance
- run cleaning and maintenance

I think most of these are in the "view internal state of certain components" category.

If the components team really wants this stuff to be "in-app", like toggling A/B tests, then Debug Drawer is clearly preferred.

**Comment by mhammond** [comment] 2018-07-24 02:23
Another anecdote: one of the biggest problems we have diagnosing the existing Sync on Fennec is the difficulty in getting logs from user devices. For almost all bugs, the relevant info is in the logs it's just impossible to get out for the average user.

We send such users to http://160.twinql.com/how-to-file-a-good-android-sync-bug, but I suspect most of them don't get past the "run adb" step :)

It seems quite possible that there isn't going to be a "one size fits all" solution here

**Comment by mcomella** [comment] 2018-07-26 21:22
> For almost all bugs, the relevant info is in the logs it's just impossible to get out for the average user.

fwiw, we could create our own logger (or use a third-party one) that keeps internal logs, for the purpose of easily filing bugs, while also printing them to logcat.

**Comment by mhammond** [comment] 2018-07-27 05:34
> fwiw, we could create our own logger (or use a third-party one) that keeps internal logs, for the purpose of easily filing bugs, while also printing them to logcat.

SGTM. An even lighter-weight option might be a separate app that hooks logcat and keeps logs up to some threshold. This would probably mean we'd need users to install this app and then reproduce their problem, but that might be a reasonable compromise and might allow us to be more aggressive in terms  of how much storage space we use for the logs - if the app is installed we can make assumptions that wouldn't necessarily be valid for the average user.

**Comment by pocmo** [comment] 2018-07-27 07:35
> fwiw, we could create our own logger (or use a third-party one) that keeps internal logs, for the purpose of easily filing bugs, while also printing them to logcat.

Related: #15 - We definitely want to be smarter about logging and not just let components blurt out things to the log without the app being in control.

> An even lighter-weight option might be a separate app that hooks logcat and keeps logs up to some threshold. 

Since Android 4.1 apps can't hold the permission to read other app's logs anymore. So we'd definitely need something inside the actual app if we want to make logs available in some form.

**Comment by colintheshots** [comment] 2018-07-27 15:51
Not only can't apps read each other's logs, but they can't stay awake anymore if the user hasn't started them recently. As tempting as it might be to envision some solution with AIDL or bound services, in recent Android versions, you'd have to operate a foreground service with a foreground notification and the user would need to have started the second app in the last week. This doesn't seem feasible.

It seems you'd want a reusable component that can store encrypted logs with some non-trivial secret and then offer the user a tool to dump them. The hardest part would be ensuring security here, as the open source app would need to know and store its secret somehow and you'd need some way to clear logs for private/incognito window data. Fabric Crashlytics basically stores up logs in a file to submit on app restart after a crash. This seems like a common model in most popular apps.

I'm not aware of existing open source tools that do this well. Stetho was written entirely about debugging a device with an ADB connection, which usually means the device is in your possession or connected to one of the better cloud testing services. It's written with the developer in mind and works admirably for that need. I haven't used Debug Drawer, but it also doesn't seem pertinent.

I feel I'd implement this from scratch on any Android project I've been on.

**Comment by csadilek** [comment] 2022-10-11 19:34
Will close this old ticket in favour of the newer and more concrete proposals:
https://github.com/mozilla-mobile/android-components/pull/8684
https://github.com/mozilla-mobile/android-components/issues/8345
https://github.com/mozilla-mobile/android-components/issues/6341

**Closed by csadilek** 2022-10-11 19:34 UTC
Labels: 🔬 Research, 🔧 tooling
