### ISSUE TITLE
Intermittent UI test failure - <MainActivityTest.checkGleanClickData>

### ISSUE THREAD

**Issue by iorgamgabriel** [mozilla-mobile/android-components#11992] opened 2022-04-12 12:25 UTC
### Firebase Test Run:
[Provide a Firebase test run report link here showcasing the problem](https://console.firebase.google.com/u/0/project/moz-android-components-230120/testlab/histories/bh.acacddb44ee28c64/matrices/5557028787407772989/executions/bs.fa6da286d7c0cd25/test-cases)

### Build: https://github.com/mozilla-mobile/android-components/pull/11991

saw in ... that this test was failing although my changes didn't touch it
disabled the test to be able to merge
FYI @Dexterp37 as I saw you wrote these tests.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20133)

**Comment by sv-ohorvath** [comment] 2022-04-15 13:33
Failed on 4/15, Nexus 6, Virtual, API Level 21: https://console.firebase.google.com/project/moz-android-components-230120/testlab/histories/bh.acacddb44ee28c64/matrices/6606697584013486508/executions/bs.d57c11ad05e04aa4/testcases/2

**Comment by sv-ohorvath** [comment] 2022-06-10 13:42
Duplicate of https://github.com/mozilla-mobile/android-components/issues/10781

**Closed by sv-ohorvath** 2022-06-10 13:42 UTC
